import { IconType } from "react-icons";
import { AiOutlineVideoCamera, AiOutlineVideoCameraAdd } from "react-icons/ai";
import { BiAnalyse, BiSolidReport } from "react-icons/bi";
import {
  BsChatDots,
  BsCloudUpload,
  BsDatabaseGear,
  BsRocketTakeoff,
} from "react-icons/bs";
import { CiMobile2, CiMoneyCheck1 } from "react-icons/ci";
import {
  FaChess,
  FaCode,
  FaDraftingCompass,
  FaRegHeart,
  FaRegStar,
  FaVial,
  FaTachometerAlt,
  FaDiceD20,
  FaDiceD6,
  FaRegFileCode,
} from "react-icons/fa";
import {
  FaDiagramProject,
  FaO,
  FaRegRectangleList,
  FaUsersRays,
} from "react-icons/fa6";
import {
  FiDatabase,
  FiKey,
  FiLayers,
  FiUmbrella,
  FiUpload,
  FiUsers,
  FiAward,
  FiCheckCircle,
  FiCodepen,
  FiTrendingUp,
  FiClock,
  FiZap,
  FiList,
} from "react-icons/fi";
import { GrHelpBook } from "react-icons/gr";
import {
  HiOutlineDesktopComputer,
  HiOutlineDocumentReport,
  HiOutlineInformationCircle,
} from "react-icons/hi";
import { ImUserTie } from "react-icons/im";
import { IoIosCodeDownload, IoMdBookmarks } from "react-icons/io";
import {
  IoCalendarNumberOutline,
  IoCalendarOutline,
  IoChatbubblesOutline,
  IoKeyOutline,
} from "react-icons/io5";
import { LiaFileContractSolid } from "react-icons/lia";
import { LuBookHeart, LuServer } from "react-icons/lu";
import {
  MdChangeHistory,
  MdOutlineCircle,
  MdOutlineCode,
  MdOutlinePermMedia,
  MdOutlineSystemUpdateAlt,
  MdOutlineWorkOutline,
  MdWebAsset,
} from "react-icons/md";
import { PiCertificate, PiFlowArrow } from "react-icons/pi";
import {
  RiApps2AiLine,
  RiCodeBlock,
  RiMegaphoneLine,
  RiOrganizationChart,
} from "react-icons/ri";
import { RxActivityLog } from "react-icons/rx";
import {
  TbAdjustmentsCog,
  TbArrowsExchange,
  TbBellShare,
  TbBolt,
  TbCalendarTime,
  TbCategory,
  TbChartInfographic,
  TbClipboardList,
  TbClockExclamation,
  TbCode,
  TbContract,
  TbFileReport,
  TbFolders,
  TbHourglassHigh,
  TbLanguage,
  TbLayoutDashboardFilled,
  TbListDetails,
  TbMoodShare,
  TbNavigationShare,
  TbNumbers,
  TbProgressCheck,
  TbServerCog,
  TbSettingsCog,
  TbShare,
  TbTimeline,
  TbUserBolt,
  TbUserHeart,
  TbUsers,
  TbUsersGroup,
  TbUserShare,
} from "react-icons/tb";
import { TiThMenuOutline } from "react-icons/ti";

export interface LinkItemProps {
  name: string;
  icon: IconType;
  iconName?: string; // Add explicit icon name to avoid minification issues
  link: string;
  role: string[];
  menuID: string;
  children: LinkItemProps[];
  isLocked?: boolean;
  isPro?: boolean;
}

export const LinkItems: LinkItemProps[] = [
  {
    name: "Dashboard",
    icon: TbLayoutDashboardFilled,
    iconName: "TbLayoutDashboardFilled",
    link: "/home",
    role: ["admin"],
    menuID: "1",
    children: [],
  },
  {
    name: "Workspace",
    icon: BsRocketTakeoff,
    iconName: "BsRocketTakeoff",
    link: "/workspaces",
    role: ["admin"],
    menuID: "1",
    isPro: false,
    children: [
      {
        name: "My Project",
        icon: FaCode,
        iconName: "FaCode",
        link: "/workspace",
        role: ["admin"],
        menuID: "1",
        isPro: false,
        children: [],
      },
      {
        name: "My Performance",
        icon: FiAward,
        iconName: "FiAward",
        link: "/performances/my-performance",
        role: ["admin"],
        menuID: "1",
        isPro: false,
        children: [],
      },
      {
        name: "Division Summary",
        icon: FiAward,
        iconName: "FiAward",
        link: "/performances/divisions/summary",
        role: ["admin"],
        menuID: "1",
        isPro: false,
        children: [],
      },
      {
        name: "Group Summary",
        icon: FiAward,
        iconName: "FiAward",
        link: "/performances/groups/summary",
        role: ["admin"],
        menuID: "1",
        isPro: false,
        children: [],
      },
      // {
      //   name: "Development",
      //   icon: MdOutlineCode,
      //   link: "/workspace/development",
      //   role: ["admin"],
      //   menuID: "1",
      //   isPro: false,
      //   children: [],
      // },
    ],
  },
  // {
  //   name: "Workspace",
  //   icon: BsRocketTakeoff,
  //   link: "/workspace",
  //   role: ["admin"],
  //   menuID: "1",
  //
  //   children: [
  //     {
  //       name: "My Project",
  //       icon: FaCode,
  //       link: "/project-development",
  //       role: ["admin"],
  //       menuID: "1",
  //
  //       children: [],
  //     },
  //   ],
  // },
  {
    name: "Requirements",
    icon: FaDraftingCompass,
    iconName: "FaDraftingCompass",
    link: "/requirements",
    role: ["admin"],
    menuID: "1",
    children: [
      // {
      //   name: "BRD",
      //   icon: MdOutlineCircle,
      //   link: "/requirements/brd",
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "RFC",
      //   icon: MdChangeHistory,
      //   link: "/requirements/rfc",
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      {
        name: "Pending Approve",
        icon: FiClock,
        iconName: "FiClock",
        link: "/requirements/approval-hub",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "BRD / RFC",
        icon: MdChangeHistory,
        iconName: "MdChangeHistory",
        link: "/requirements/brd-rfc",
        role: ["admin"],
        menuID: "1",
        children: [],
      },

      {
        name: "Prerequisites",
        icon: MdChangeHistory,
        iconName: "MdChangeHistory",
        isPro: true,
        link: "/coming-soon",
        role: ["admin"],

        menuID: "1",
        children: [],
      },
      // {
      //   name: "Pending Review",
      //   icon: MdOutlineCircle,
      //   link: "/requirements/pending-reviews",
      //     role: ["admin"],
      //     menuID: "1",
      //     children: [],
      // // },
    ],
  },
  {
    name: "Projects",
    icon: FaDiagramProject,
    iconName: "FaDiagramProject",
    link: "/projects",
    role: ["admin"],
    isPro: false,
    menuID: "1",
    children: [
      {
        name: "Pending Approve",
        icon: FiClock,
        iconName: "FiClock",
        link: "/projects/pending-approve",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Internal Development",
        icon: FaCode,
        iconName: "FaCode",
        link: "/projects-manager?reqType=brd",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Procurement",
        icon: TbContract,
        iconName: "TbContract",
        link: "/projects-procurements",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "RFC",
        icon: FaCode,
        iconName: "FaCode",
        link: "/projects-manager?reqType=rfc",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Deployment",
        icon: BsCloudUpload,
        iconName: "BsCloudUpload",
        link: "/projects-deployments",
        role: ["admin"],
        isPro: true,
        menuID: "1",
        children: [],
      },
      {
        name: "Timeline Simulation",
        icon: TbTimeline,
        iconName: "TbTimeline",
        link: "/coming-soon",
        role: ["admin"],
        isPro: true,
        menuID: "1",
        children: [],
      },
    ],
  },
  {
    name: "Vendor Management",
    icon: FiUmbrella,
    iconName: "FiUmbrella",
    link: "/vendor-management",
    isPro: false,
    role: ["admin"],
    menuID: "1",
    children: [
      {
        name: "Vendor List",
        icon: LiaFileContractSolid,
        iconName: "LiaFileContractSolid",
        link: "/vendor-management",
        isPro: false,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Work Program",
        icon: FiUmbrella,
        iconName: "FiUmbrella",
        link: "/coming-soon",
        isPro: true,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Payment Tracking",
        icon: FiLayers,
        iconName: "FiLayers",
        link: "/coming-soon",
        isPro: true,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
    ],
  },
  {
    name: "Resource Management",
    icon: TbUsers,
    iconName: "TbUsers",
    link: "/resource-monitor",
    role: ["admin"],
    menuID: "1",
    children: [
      // {
      //   name: "Resource Load Tracking",
      //   icon: TbUserHeart,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Resource Allocation",
      //   icon: TbUserShare,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Resource Availability",
      //   icon: TbUserBolt,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
    ],
  },

  {
    name: "Management Apps",
    icon: FaDiceD20,
    iconName: "FaDiceD20",
    link: "/master-data/Application",
    role: ["admin"],
    menuID: "1",
    children: [
      {
        name: "Data Applications",
        icon: FaDiceD6,
        iconName: "FaDiceD6",
        link: "/master-data/Application",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Matrix & Criteria",
        icon: FiList,
        iconName: "FiList",
        link: "/master-data/conf-matrix-criteria-apps",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Assessment of Critical Apps",
        icon: FaRegRectangleList,
        iconName: "FaRegRectangleList",
        link: "/report/apps-assessments",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Pending Approve Assessment Apps",
        icon: FiClock,
        iconName: "FiClock",
        link: "/report/apps-assessments-pending-approve",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Upload Report Apps",
        icon: FaRegFileCode,
        iconName: "FaRegFileCode",
        link: "/report/upload-report-assessments-apps",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
    ],
  },
  {
    name: "Meeting ",
    icon: AiOutlineVideoCamera,
    iconName: "AiOutlineVideoCamera",
    link: "/coming-soon",
    isPro: true,
    role: ["admin"],

    menuID: "1",
    children: [
      {
        name: "Meeting Calendar",
        icon: IoCalendarOutline,
        iconName: "IoCalendarOutline",
        link: "/coming-soon",
        role: ["admin"],

        isPro: true,
        menuID: "1",
        children: [],
      },
    ],
  },

  // {
  //   name: "Projects(ALT)",
  //   icon: FaDiagramProject,
  //   link: "/projects-alt",
  //   role: ["admin"],
  //   menuID: "1",
  //   children: [
  //     {
  //       name: "Internal Development",
  //       icon: FaCode,
  //       link: "/projects-alt/internal-development",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //   ],
  // },

  {
    name: "Reports",
    icon: BiSolidReport,
    iconName: "BiSolidReport",
    link: "/reports",
    role: ["admin"],
    isPro: false,
    menuID: "1",
    children: [
      {
        name: "Historical Report",
        icon: FiClock,
        iconName: "FiClock",
        link: "/reports/dashboard-portfolio",
        role: ["admin"],
        isPro: false,
        menuID: "1",
        children: [
          {
            name: "[H] Dashboard Portfolio",
            icon: BiSolidReport,
            iconName: "BiSolidReport",
            link: "/reports/dashboard-portfolio",
            role: ["admin"],
            isPro: false,
            menuID: "1",
            children: [],
          },
          {
            name: "[H] Projects Active List Report",
            icon: TbListDetails,
            iconName: "TbListDetails",
            link: "/reports/project-active-portfolio",
            role: ["admin"],
            isPro: false,
            menuID: "1",
            children: [],
          },
          {
            name: "[H] Projects Close List Report",
            icon: TbListDetails,
            iconName: "TbListDetails",
            link: "/reports/project-close-portfolio",
            role: ["admin"],
            isPro: false,
            menuID: "1",
            children: [],
          },
        ],
      },
      {
        name: "Realtime Report",
        icon: FiZap,
        iconName: "FiZap",
        link: "/reports/dashboard-portfolio",
        role: ["admin"],
        isPro: false,
        menuID: "1",
        children: [
          {
            name: "[RT] Dashboard Realtime",
            icon: BiSolidReport,
            iconName: "BiSolidReport",
            link: "/reports/dashboard-portfolio-real-time",
            role: ["admin"],
            isPro: false,
            menuID: "1",
            children: [],
          },

          {
            name: "[RT] Portfolio",
            icon: BiSolidReport,
            iconName: "BiSolidReport",
            link: "/reports/project-portfolio",
            role: ["admin"],
            isPro: false,
            menuID: "1",
            children: [],
          },
        ],
      },

      // {
      //   name: "Requirement Portfolio",
      //   icon: BiSolidReport,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //   isPro: false,
      //   menuID: "1",
      //   children: [],
      // },

      // {
      //   name: "Master Report Snapshot",
      //   icon: TbFileReport,
      //   iconName: "TbFileReport",
      //   link: "/report/master-report-snapshot",
      //   role: ["admin"],
      //   isPro: false,
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Application & Feature",
      //   icon: RiApps2AiLine,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //
      //   menuID: "1",
      //   children: [],
      // },
      // {

      //   name: "Project Team",
      //   icon: TbUsersGroup,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Executive Summary",
      //   icon: ImUserTie,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //
      //   menuID: "1",
      //   children: [],
      // },
    ],
  },

  {
    name: "Teams Performances",
    icon: FaRegStar,
    iconName: "FaRegStar",
    link: "/performances",
    isPro: false,
    role: ["admin"],
    menuID: "1",
    children: [
      {
        name: "Performances Divisions",
        icon: FaRegStar,
        iconName: "FaRegStar",
        link: "/performances/divisions",
        isPro: false,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Performances Group",
        icon: FaRegStar,
        iconName: "FaRegStar",
        link: "/performances/groups",
        isPro: false,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Performances Teams",
        icon: FaRegStar,
        iconName: "FaRegStar",
        link: "/performances/teams",
        isPro: false,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
    ],
  },
  {
    name: "Assets Management",
    icon: FaRegStar,
    iconName: "FaRegStar",
    link: "/coming-soon",
    isPro: true,
    role: ["admin"],
    menuID: "1",

    children: [
      //   {
      //     name: "S",
      //     icon: MdWebAsset,
      //     link: "/coming-soon",
      //     role: ["admin"],
      //
      //     menuID: "1",
      //     children: [],
      //   }
      // {
      //   name: "Hardware",
      //   icon: LuServer,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "License & Subscriptions",
      //   icon: IoKeyOutline,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //
      //   menuID: "1",
      //   children: [],
      // },
    ],
  },
  {
    name: "DevOps",
    icon: BsDatabaseGear,
    iconName: "BsDatabaseGear",
    link: "/coming-soon",
    role: ["admin"],
    isPro: true,

    menuID: "1",
    children: [
      {
        name: "DevOps ",
        icon: BsDatabaseGear,
        iconName: "BsDatabaseGear",
        link: "/coming-soon",
        role: ["admin"],

        isPro: true,
        menuID: "1",
        children: [],
      },
      // {
      //   name: "DevOps Integration",
      //   icon: IoIosCodeDownload,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Source Code Repository",
      //   icon: RiCodeBlock,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Engineer On Site (EoS) Report",
      //   icon: HiOutlineDocumentReport,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Route Cause Analysis (RCA)",
      //   icon: BiAnalyse,
      //   link: "/coming-soon",
      //   role: ["admin"],
      //
      //   menuID: "1",
      //   children: [],
      // },
      {
        name: "Maintenance Report",
        icon: TbFileReport,
        iconName: "TbFileReport",
        link: "/coming-soon",
        role: ["admin"],

        isPro: true,
        menuID: "1",
        children: [],
      },
    ],
  },
  // {
  //   name: "Collaboration & Sharing",
  //   icon: TbShare,
  //   link: "/coming-soon",
  //   role: ["admin"],
  //
  //   menuID: "1",
  //   children: [
  //     {
  //       name: "Mention & Notification",
  //       icon: TbBellShare,
  //       link: "/coming-soon",
  //       role: ["admin"],
  //
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Internal Sharing",
  //       icon: TbMoodShare,
  //       link: "/coming-soon",
  //       role: ["admin"],
  //
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "External Collaboration",
  //       icon: TbNavigationShare,
  //       link: "/coming-soon",
  //       role: ["admin"],
  //
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Chat",
  //       icon: IoChatbubblesOutline,
  //       link: "/coming-soon",
  //       role: ["admin"],
  //
  //       menuID: "1",
  //       children: [],
  //     },
  //   ],
  // },
  // {
  //   name: "Team Manager",
  //   icon: FaChess,
  //   link: "/teams",
  //   role: ["admin"],
  //   menuID: "1",
  //   children: [],
  // },
  // {
  //   name: "Server Manager",
  //   icon: CiServer,
  //   link: "/server-manager",
  // role: ["admin"],
  // menuID: "1",
  // children: [],
  // },
  {
    name: "Knowledge Base",
    icon: GrHelpBook,
    iconName: "GrHelpBook",
    link: "/coming-soon",
    role: ["admin"],

    menuID: "1",
    children: [
      {
        name: "Bjb Ask",
        icon: BsChatDots,
        iconName: "BsChatDots",
        link: "/coming-soon",
        role: ["admin"],
        isPro: true,
        menuID: "1",
        children: [],
      },
      {
        name: "Bjb Apps User Guide",
        icon: LuBookHeart,
        iconName: "LuBookHeart",
        link: "/show-flow",
        role: ["admin"],

        menuID: "1",
        children: [],
      },
      {
        name: "Document Templates",
        icon: IoMdBookmarks,
        iconName: "IoMdBookmarks",
        link: "/coming-soon",
        role: ["admin"],
        isPro: true,
        menuID: "1",
        children: [],
      },
    ],
  },
  {
    name: "Master Data",
    icon: FiDatabase,
    iconName: "FiDatabase",
    link: "/master-data",
    role: ["admin"],
    menuID: "1",
    children: [
      {
        name: "Master Organizations",
        icon: RiOrganizationChart,
        iconName: "RiOrganizationChart",
        link: "/master-data/organizations",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Master Team",
        icon: FaUsersRays,
        iconName: "FaUsersRays",
        link: "/teams-center",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Master Workflow",
        icon: PiFlowArrow,
        iconName: "PiFlowArrow",
        link: "/master-data/workflow",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Master SDLC Flow",
        icon: TbTimeline,
        iconName: "TbTimeline",
        link: "/master-data/sdlc-flow",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Master Users",
        icon: FiUsers,
        iconName: "FiUsers",
        link: "/master-data/users",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Master User PIC",
        icon: FiKey,
        iconName: "FiKey",
        link: "/coming-soon",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Master Specialization",
        icon: FiAward,
        iconName: "FiAward",
        link: "/master-data/specialization",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Master Certification",
        icon: TbChartInfographic,
        iconName: "TbChartInfographic",
        link: "/master-data/certification",
        isPro: true,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Master Programming Language",
        icon: TbSettingsCog,
        iconName: "TbSettingsCog",
        link: "/master-data/masterLanguage",
        isPro: true,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
    ],
  },
  {
    name: "Access Configurations",
    icon: IoKeyOutline,
    iconName: "IoKeyOutline",
    link: "/master-data/authorize-groups",
    role: ["admin"],
    isPro: false,
    menuID: "1",
    children: [
      {
        name: "Master Menu",
        icon: TiThMenuOutline,
        iconName: "TiThMenuOutline",
        link: "/master-data/menus",
        role: ["admin"],
        menuID: "1",

        children: [],
      },
      {
        name: "Sys Module Group",
        icon: TbUsersGroup,
        iconName: "TbUsersGroup",
        link: "/master-data/sys-module-group",
        role: ["admin"],
        isPro: false,
        menuID: "1",
        children: [],
      },
      {
        name: "Authorize Group",
        icon: TbUsersGroup,
        iconName: "TbUsersGroup",
        link: "/master-data/authorize-groups",
        role: ["admin"],
        isPro: false,
        menuID: "1",
        children: [],
      },
      // {
      //   name: "Master Organization Structure",
      //   icon: RiOrganizationChart,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Master Certifications",
      //   icon: PiCertificate,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Master Programming Language",
      //   icon: MdOutlineCode,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Master Specializations",
      //   icon: TbBolt,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
    ],
  },
  // {
  //   name: "Menu Name",
  //   icon: TbBolt, // icon proefer
  //   link: "/coming-soon", // constant
  //    // constant
  //   role: ["admin"], // constant
  //   menuID: "1", // constant
  //   children: [
  //     {
  //       name: "Menu Name",
  //       icon: TbBolt, // icon proefer
  //       link: "/coming-soon", // constant
  //        // constant
  //       role: ["admin"], // constant
  //       menuID: "1", // constant
  //       children: [], // Sub here
  //     },
  //   ], // Sub here
  // },
  {
    name: "Parameter ",
    icon: TbAdjustmentsCog, // general "settings/parameters" icon
    iconName: "FTbAdjustmentsCogiKey",
    link: "/coming-soon",
    role: ["admin"],
    isPro: false,
    menuID: "1",
    children: [
      {
        name: "Parameter Constant",
        icon: FiKey,
        iconName: "FiKey",
        link: "/master-data/constants-data",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      // {
      //   name: "BRD & RFC Status",
      //   icon: TbListDetails,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Deployment Status",
      //   icon: TbArrowsExchange,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Project Status",
      //   icon: TbProgressCheck,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Project Indicators",
      //   icon: TbChartInfographic,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Project Types",
      //   icon: TbFolders,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Project Characteristics",
      //   icon: TbCategory,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Development Status",
      //   icon: TbServerCog,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Deliverables Status",
      //   icon: TbClipboardList,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      // {
      //   name: "Maintenance Types & Categories",
      //   icon: TbAdjustmentsCog,
      //   link: "/coming-soon",
      //
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
      {
        name: "Parameter Language Mapping",
        icon: TbLanguage,
        iconName: "TbLanguage",
        link: "/coming-soon",
        isPro: true,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Project Codes",
        icon: TbCode,
        iconName: "TbCode",
        link: "/coming-soon",
        isPro: true,
        role: ["admin"],
        menuID: "1",
        children: [],
      },
    ],
  },
  {
    name: "System Parameters",
    icon: TbSettingsCog, // general system/settings icon
    iconName: "TbSettingsCog",
    link: "/coming-soon",
    isPro: false,

    role: ["admin"],
    menuID: "1",
    children: [
      {
        name: "Calender Engine",
        icon: TbCalendarTime,
        iconName: "TbCalendarTime",
        link: "/coming-soon",

        role: ["admin"],
        menuID: "1",
        isPro: true,
        children: [],
      },
      {
        name: "Session Timeout",
        icon: TbHourglassHigh,
        iconName: "TbHourglassHigh",
        link: "/coming-soon",

        role: ["admin"],
        menuID: "1",
        isPro: true,
        children: [],
      },
      {
        name: "System Cut-Off Time",
        icon: TbClockExclamation,
        iconName: "TbClockExclamation",
        link: "/coming-soon",

        role: ["admin"],
        menuID: "1",
        isPro: true,
        children: [],
      },
      {
        name: "Announcements",
        icon: RiMegaphoneLine,
        iconName: "RiMegaphoneLine",
        link: "/coming-soon",

        role: ["admin"],
        menuID: "1",
        isPro: true,
        children: [],
      },
      {
        name: "Time Tracking",
        icon: TbTimeline,
        iconName: "TbTimeline",
        link: "/coming-soon",

        role: ["admin"],
        menuID: "1",
        isPro: true,
        children: [],
      },
      {
        name: "Sequences Config",
        icon: TbNumbers,
        iconName: "TbNumbers",
        link: "/master-data/sequences-config",

        role: ["admin"],
        menuID: "1",
        isPro: false,
        children: [],
      },
    ],
  },
  // {
  //   name: "Advanced",
  //   icon: TbBolt,
  //   link: "/advanced",
  //
  //   role: ["admin"],
  //   menuID: "1",
  //   children: [
  //     {
  //       name: "Pro Dashboard",
  //       icon: TbLayoutDashboardFilled,
  //       link: "/advanced/pro-dashboard",
  //
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //   ],
  // },
  // {
  //   name: "About",
  //   icon: HiOutlineInformationCircle,
  //   link: "/coming-soon",
  //
  //   role: ["admin"],
  //   menuID: "1",
  //   children: [
  //     {
  //       name: "Bjb Apps Web",
  //       icon: FaRegHeart,
  //       link: "/coming-soon",
  //
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Bjb Apps Mobile",
  //       icon: CiMobile2,
  //       link: "/coming-soon",
  //
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Hybrid Methodologies",
  //       icon: FaVial,
  //       link: "/coming-soon",
  //
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //   ],
  // },
  // {
  //   name: "Add-Ons",
  //   icon: FaO,
  //   link: "/coming-soon",
  //
  //   role: ["admin"],
  //   menuID: "1",
  //   children: [
  //     {
  //       name: "System Integrations",
  //       icon: MdOutlineSystemUpdateAlt,
  //       link: "/coming-soon",
  //
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Bjb Apps Mobile",
  //       icon: CiMobile2,
  //       link: "/coming-soon",
  //
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //   ],
  // },
  {
    name: "Import Data",
    icon: FiUpload,
    iconName: "FiUpload",
    link: "/projects/import",
    role: ["admin"],
    menuID: "1",
    children: [
      {
        name: "Import Data Project",
        icon: FiUpload,
        iconName: "FiUpload",
        link: "/projects/import",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      {
        name: "Import Legacy Projects",
        icon: BsCloudUpload,
        iconName: "BsCloudUpload",
        link: "/projects/import-legacy",
        role: ["admin"],
        menuID: "1",
        children: [],
      },
      // {
      //   name: "Import Applications",
      //   icon: RiApps2AiLine,
      //   link: "/projects/import-applications",
      //   role: ["admin"],
      //   menuID: "1",
      //   children: [],
      // },
    ],
  },
  {
    name: "File Archive",
    icon: MdOutlinePermMedia,
    iconName: "MdOutlinePermMedia",
    link: "/file-archives",
    role: ["admin"],
    menuID: "1",
    isPro: true,
    children: [],
  },
  {
    name: "Audit Trail",
    icon: RxActivityLog,
    iconName: "RxActivityLog",
    link: "/audit-trail",
    isPro: false,
    role: ["admin"],
    menuID: "1",
    children: [],
  },

  // {
  //   name: "Profile",
  //   icon: FiUser,
  //   link: "/profile",
  // role: ["admin"],
  // menuID: "1",
  // children: [],
  // },
  // {
  //   name: "Pricing",
  //   icon: FiDollarSign,
  //   link: "/pricing",
  // role: ["admin"],
  // menuID: "1",
  // children: [],
  //   isLocked: true,
  // },
  // {
  //   name: "Avtivities",
  //   icon: RxActivityLog,
  //   link: "/activities",
  // role: ["admin"],
  // menuID: "1",
  // children: [],
  //   isLocked: true,
  // },
  // {
  //   name: "User Config",
  //   icon: FaUsersGear,
  //   link: "/users",
  // role: ["admin"],
  // menuID: "1",
  //   children: [
  //     {
  //       name: "User Manager",
  //       icon: FaUserPlus,
  //       link: "/users",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Master Role Sys",
  //       icon: FaUsersRays,
  //       link: "/users/roles",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Master Division",
  //       icon: FaFire,
  //       link: "/users/divisions",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //   ],
  // },
  // {
  //   name: "Example Page",
  //   icon: FaRegFolderOpen,
  //   link: "#",
  // role: ["admin"],
  // menuID: "1",
  //   children: [
  //     {
  //       name: "Kanban",
  //       icon: BsKanban,
  //       link: "/kanban",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Kanban Alt",
  //       icon: BsKanban,
  //       link: "/kanban-alt",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Calendar",
  //       icon: IoCalendarNumberOutline,
  //       link: "/calendar",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Drop Zone",
  //       icon: MdOutlinePermMedia,
  //       link: "/dropzone",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "User",
  //       icon: FiUser,
  //       link: "/users",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //     {
  //       name: "Settings",
  //       icon: FiSettings,
  //       link: "/settings",
  //       role: ["admin"],
  //       menuID: "1",
  //       children: [],
  //     },
  //   ],
  // },
];
