"use client";

import { useState } from "react";
import {
  Alert,
  AlertIcon,
  Badge,
  Box,
  Button,
  Card,
  CardBody,
  CardHeader,
  Divider,
  Flex,
  FormControl,
  FormErrorMessage,
  FormLabel,
  Grid,
  GridItem,
  Heading,
  HStack,
  Icon,
  Input,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  ModalContent,
  ModalOverlay,
  NumberInput,
  NumberInputField,
  NumberInputStepper,
  NumberIncrementStepper,
  NumberDecrementStepper,
  Select as ChakraSelect,
  Slider,
  SliderTrack,
  SliderFilledTrack,
  SliderThumb,
  Switch,
  Text,
  Textarea,
  useColorMode,
  useDisclosure,
  VStack,
} from "@chakra-ui/react";
import {
  FiAlertCircle,
  FiAlertTriangle,
  FiBriefcase,
  FiCalendar,
  FiCheck,
  FiCheckCircle,
  FiDollarSign,
  FiInfo,
  FiLock,
  FiPlus,
  FiRepeat,
  FiRefreshCw,
  FiSave,
  FiShield,
  FiSliders,
  FiTrash2,
  FiUserCheck,
} from "react-icons/fi";
import { useFormik } from "formik";
import * as yup from "yup";

import useVendor, {
  ContractTopInsertPayload,
  VendorContractInsertPayload,
  VendorContractResponse,
} from "@/app/services/useVendor";
import { useToastHelper } from "@/app/helper/ToastMessagesHelper";
import { RES_CODE_OK } from "@/app/constants/applicationConstants";
import { formatIDR } from "@/app/components/CardContract";
import CurrencyInput from "@/app/components/inputProps/currencyInput";
import ModalTopAutoAdjust from "../../register/components/ModalTopAutoAdjust";

interface ContractEditTabPanelProps {
  contract: VendorContractResponse;
  tokenData: string;
  onRefreshData: () => void;
}

const validationSchema = yup.object({
  corpNumber: yup.string().required("Corporate SPK Number is required"),
  corpName: yup.string().required("Project Title is required"),
  contractNumber: yup.string().required("Contract Number is required"),
  contractDate: yup.string().required("Contract Date is required"),
  workValue: yup.number().min(0, "Work value cannot be negative"),
});

export const ContractEditTabPanel = ({
  contract,
  tokenData,
  onRefreshData,
}: ContractEditTabPanelProps) => {
  const { colorMode } = useColorMode();
  const { InsertContract } = useVendor();
  const showToast = useToastHelper();

  const confirmModal = useDisclosure();
  const topAutoAdjustModal = useDisclosure();

  const selectedProject = contract.projectId
    ? {
        id: contract.projectId,
        projectCode: contract.projectCode || contract.projectNo,
        projectName: contract.projectName,
        proOwnerDivisionName: contract.proOwnerDivisionName,
        proOwnerDirectorateName: contract.proOwnerDirectorateName,
        sdlcStageName: contract.sdlcStageName,
      }
    : null;

  // Detect if payment workflow is running or has been partially/fully paid
  const isPaymentRunning = (contract.topList || []).some(
    (t) =>
      (t.topStatus && ["SUBMITTED", "VERIFIED", "APPROVED", "PAID"].includes(t.topStatus.toUpperCase())) ||
      (t.topAttachments && t.topAttachments.length > 0)
  );

  const paidTopCount = (contract.topList || []).filter(
    (t) => t.topStatus && t.topStatus.toUpperCase() === "PAID"
  ).length;

  const inProgressTopCount = (contract.topList || []).filter(
    (t) => t.topStatus && ["SUBMITTED", "VERIFIED", "APPROVED"].includes(t.topStatus.toUpperCase())
  ).length;

  const [showTopDates, setShowTopDates] = useState<boolean>(
    (contract.topList || []).some((t) => !!t.topDate || !!t.billingPeriodStart)
  );
  const [countdown, setCountdown] = useState<number>(5);
  const [canSubmit, setCanSubmit] = useState<boolean>(false);
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);

  const initialTopList: ContractTopInsertPayload[] = (contract.topList || []).map((t) => ({
    id: t.id,
    stepOrder: t.stepOrder,
    topValues: t.topValues || 0,
    topDate: t.topDate ? t.topDate.split("T")[0] : "",
    topDescriptions: t.topDescriptions || "",
    topStatus: t.topStatus || "ACTIVE",
    billingPeriodStart: t.billingPeriodStart ? t.billingPeriodStart.split("T")[0] : "",
    billingPeriodEnd: t.billingPeriodEnd ? t.billingPeriodEnd.split("T")[0] : "",
    isAutoGenerated: !!t.isAutoGenerated,
  }));

  const formik = useFormik<VendorContractInsertPayload>({
    initialValues: {
      id: contract.id,
      projectId: contract.projectId || "",
      vendorId: contract.vendorId,
      corpNumber: contract.corpNumber || "",
      corpName: contract.corpName || "",
      contractNumber: contract.contractNumber || "",
      contractDate: contract.contractDate ? contract.contractDate.split("T")[0] : new Date().toISOString().split("T")[0],
      workValue: contract.workValue || 0,
      note: contract.note || "",
      contractStartDate: contract.contractStartDate ? contract.contractStartDate.split("T")[0] : "",
      contractEndDate: contract.contractEndDate ? contract.contractEndDate.split("T")[0] : "",
      worksStartDate: contract.worksStartDate ? contract.worksStartDate.split("T")[0] : "",
      worksEndDate: contract.worksEndDate ? contract.worksEndDate.split("T")[0] : "",
      warrantyStartDate: contract.warrantyStartDate ? contract.warrantyStartDate.split("T")[0] : "",
      warrantyEndDate: contract.warrantyEndDate ? contract.warrantyEndDate.split("T")[0] : "",
      maintenanceStartDate: contract.maintenanceStartDate ? contract.maintenanceStartDate.split("T")[0] : "",
      maintenanceEndDate: contract.maintenanceEndDate ? contract.maintenanceEndDate.split("T")[0] : "",
      othersTimeline: contract.othersTimeline || "",
      termOfPayment: contract.termOfPayment || "",
      performanceGuaranteeStartDate: contract.performanceGuaranteeStartDate ? contract.performanceGuaranteeStartDate.split("T")[0] : "",
      performanceGuaranteeEndDate: contract.performanceGuaranteeEndDate ? contract.performanceGuaranteeEndDate.split("T")[0] : "",
      performanceGuaranteeValues: contract.performanceGuaranteeValues || 0,
      maintenanceWarrantyStartDate: contract.maintenanceWarrantyStartDate ? contract.maintenanceWarrantyStartDate.split("T")[0] : "",
      maintenanceWarrantyEndDate: contract.maintenanceWarrantyEndDate ? contract.maintenanceWarrantyEndDate.split("T")[0] : "",
      maintenanceWarrantyValues: contract.maintenanceWarrantyValues || 0,
      cavexValues: contract.cavexValues || 0,
      capexPercentage: contract.capexPercentage || 0,
      ovexValues: contract.ovexValues || 0,
      ovexPercentage: contract.ovexPercentage || 0,
      status: contract.status || "ACTIVE",
      contractBillingType: contract.contractBillingType || "MILESTONE",
      subscriptionPeriodValue: contract.subscriptionPeriodValue || 0,
      subscriptionAutoRenew: !!contract.subscriptionAutoRenew,
      items: [],
      topList: initialTopList.length > 0 ? initialTopList : [{ stepOrder: 1, topValues: 0, topDate: "", topDescriptions: "", topStatus: "ACTIVE" }],
    },
    validationSchema,
    onSubmit: async () => {
      handleOpenConfirm();
    },
  });

  // Countdown handler for safety confirmation modal
  const handleOpenConfirm = () => {
    const currentWorkVal = formik.values.workValue || 0;
    const currentPaidSum = (formik.values.topList || [])
      .filter((t) => t.topStatus && t.topStatus.toUpperCase() === "PAID")
      .reduce((acc, curr) => acc + (curr.topValues || 0), 0);

    if (currentWorkVal < currentPaidSum) {
      showToast({
        description: `Cannot save: Total Work Value (${formatIDR(currentWorkVal)}) is lower than already disbursed amount (${formatIDR(currentPaidSum)}).`,
        statusToast: "error",
      });
      return;
    }

    const currentTotalTop = (formik.values.topList || []).reduce((acc, curr) => acc + (curr.topValues || 0), 0);

    // Enforce 100% balance for Milestone contracts
    if (formik.values.contractBillingType === "MILESTONE" && currentTotalTop !== currentWorkVal) {
      showToast({
        description: `Milestone contract requires 100% balance between TOP schedule (${formatIDR(currentTotalTop)}) and Total Work Value (${formatIDR(currentWorkVal)}). Variance: ${formatIDR(Math.abs(currentTotalTop - currentWorkVal))}. Please use Auto-Balance or Auto-Sync.`,
        statusToast: "warning",
      });
      return;
    }

    setCountdown(5);
    setCanSubmit(false);
    confirmModal.onOpen();

    let count = 5;
    const interval = setInterval(() => {
      count -= 1;
      setCountdown(count);
      if (count <= 0) {
        clearInterval(interval);
        setCanSubmit(true);
      }
    }, 1000);
  };

  // Synchronized CAPEX/OPEX Calculations
  const handleTotalWorkValueChange = (newWorkValue: number) => {
    formik.setFieldValue("workValue", newWorkValue);
    const capexPct = formik.values.capexPercentage || 0;
    const cavexVal = (capexPct / 100) * newWorkValue;
    const ovexVal = Math.max(0, newWorkValue - cavexVal);
    formik.setFieldValue("cavexValues", cavexVal);
    formik.setFieldValue("ovexValues", ovexVal);
  };

  const handleCapexValueChange = (inputVal: number) => {
    const totalWV = formik.values.workValue || 0;
    const boundedVal = Math.min(Math.max(0, inputVal), totalWV);
    const capexPct = totalWV > 0 ? parseFloat(((boundedVal / totalWV) * 100).toFixed(2)) : 0;
    const ovexVal = Math.max(0, totalWV - boundedVal);
    const ovexPct = parseFloat((100 - capexPct).toFixed(2));

    formik.setFieldValue("cavexValues", boundedVal);
    formik.setFieldValue("capexPercentage", capexPct);
    formik.setFieldValue("ovexValues", ovexVal);
    formik.setFieldValue("ovexPercentage", ovexPct);
  };

  const handleCapexPercentageChange = (inputPct: number) => {
    const totalWV = formik.values.workValue || 0;
    const boundedPct = Math.min(Math.max(0, inputPct), 100);
    const cavexVal = (boundedPct / 100) * totalWV;
    const ovexPct = parseFloat((100 - boundedPct).toFixed(2));
    const ovexVal = Math.max(0, totalWV - cavexVal);

    formik.setFieldValue("capexPercentage", boundedPct);
    formik.setFieldValue("cavexValues", cavexVal);
    formik.setFieldValue("ovexPercentage", ovexPct);
    formik.setFieldValue("ovexValues", ovexVal);
  };

  const handleOvexValueChange = (inputVal: number) => {
    const totalWV = formik.values.workValue || 0;
    const boundedVal = Math.min(Math.max(0, inputVal), totalWV);
    const ovexPct = totalWV > 0 ? parseFloat(((boundedVal / totalWV) * 100).toFixed(2)) : 0;
    const cavexVal = Math.max(0, totalWV - boundedVal);
    const capexPct = parseFloat((100 - ovexPct).toFixed(2));

    formik.setFieldValue("ovexValues", boundedVal);
    formik.setFieldValue("ovexPercentage", ovexPct);
    formik.setFieldValue("cavexValues", cavexVal);
    formik.setFieldValue("capexPercentage", capexPct);
  };

  const handleOvexPercentageChange = (inputPct: number) => {
    const totalWV = formik.values.workValue || 0;
    const boundedPct = Math.min(Math.max(0, inputPct), 100);
    const ovexVal = (boundedPct / 100) * totalWV;
    const capexPct = parseFloat((100 - boundedPct).toFixed(2));
    const cavexVal = Math.max(0, totalWV - ovexVal);

    formik.setFieldValue("ovexPercentage", boundedPct);
    formik.setFieldValue("ovexValues", ovexVal);
    formik.setFieldValue("capexPercentage", capexPct);
    formik.setFieldValue("cavexValues", cavexVal);
  };

  // Periodic Rate (Rp. per cycle) change handler - Adjusts UNPAID steps only & balances Total Work Value
  const handlePeriodicRateChange = (newRate: number) => {
    formik.setFieldValue("subscriptionPeriodValue", newRate);

    const updatedTopList = (formik.values.topList || []).map((step) => {
      const isPaid = step.topStatus && step.topStatus.toUpperCase() === "PAID";
      if (isPaid) return step; // Preserve historical paid amount
      return {
        ...step,
        topValues: newRate,
      };
    });

    formik.setFieldValue("topList", updatedTopList);

    // Auto-update Total Work Value & CAPEX/OPEX to match new schedule
    const newTotalWV = updatedTopList.reduce((acc, curr) => acc + (curr.topValues || 0), 0);
    handleTotalWorkValueChange(newTotalWV);
  };

  // Quick Subscription Schedule Generator / Date Re-aligner for Edit mode (Preserves PAID steps!)
  const handleQuickGenerateSubscriptionTop = (billingType?: string, customStart?: string, customEnd?: string) => {
    const type = billingType || formik.values.contractBillingType || "SUBSCRIPTION_MONTHLY";
    const startDateStr = customStart || formik.values.contractStartDate;
    const endDateStr = customEnd || formik.values.contractEndDate;

    const currentTopList = formik.values.topList || [];
    const paidSteps = currentTopList.filter((t) => t.topStatus && t.topStatus.toUpperCase() === "PAID");
    const rate = formik.values.subscriptionPeriodValue || 0;

    let startForUnpaid: Date;
    if (paidSteps.length > 0) {
      // Start immediately after the last paid period end
      const lastPaid = paidSteps[paidSteps.length - 1];
      const lastPaidEnd = lastPaid.billingPeriodEnd || lastPaid.topDate;
      if (lastPaidEnd) {
        const lastDate = new Date(lastPaidEnd);
        startForUnpaid = new Date(lastDate.getFullYear(), lastDate.getMonth(), lastDate.getDate() + 1);
      } else {
        startForUnpaid = startDateStr ? new Date(startDateStr) : new Date();
      }
    } else {
      startForUnpaid = startDateStr ? new Date(startDateStr) : new Date();
    }

    let end = endDateStr
      ? new Date(endDateStr)
      : new Date(startForUnpaid.getFullYear() + 1, startForUnpaid.getMonth(), startForUnpaid.getDate());

    if (isNaN(startForUnpaid.getTime())) startForUnpaid = new Date();
    if (isNaN(end.getTime()) || end <= startForUnpaid) {
      if (paidSteps.length > 0) {
        formik.setFieldValue("topList", paidSteps);
        const sum = paidSteps.reduce((acc, curr) => acc + (curr.topValues || 0), 0);
        handleTotalWorkValueChange(sum);
        return;
      }
      end = new Date(startForUnpaid.getFullYear() + 1, startForUnpaid.getMonth(), startForUnpaid.getDate());
    }

    const stepMonths =
      type === "SUBSCRIPTION_ANNUAL"
        ? 12
        : type === "SUBSCRIPTION_SEMI_ANNUAL"
        ? 6
        : type === "SUBSCRIPTION_QUARTERLY"
        ? 3
        : 1;

    const pad = (n: number) => n.toString().padStart(2, "0");
    const formatYMD = (d: Date) =>
      `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;

    const newUnpaidList: ContractTopInsertPayload[] = [];
    let currentPeriodStart = new Date(startForUnpaid);
    let step = paidSteps.length + 1;

    const freqLabel =
      type === "SUBSCRIPTION_ANNUAL"
        ? "Year"
        : type === "SUBSCRIPTION_SEMI_ANNUAL"
        ? "Semester"
        : type === "SUBSCRIPTION_QUARTERLY"
        ? "Quarter"
        : "Month";

    while (currentPeriodStart < end && step <= 120) {
      const nextMonthTarget = new Date(
        currentPeriodStart.getFullYear(),
        currentPeriodStart.getMonth() + stepMonths,
        0
      );
      const periodEnd = nextMonthTarget > end ? new Date(end) : nextMonthTarget;

      const monthName = currentPeriodStart.toLocaleDateString("en-US", {
        month: "short",
        year: "numeric",
      });

      newUnpaidList.push({
        stepOrder: step,
        topValues: rate,
        topDescriptions: `Subscription ${freqLabel} #${step} (${monthName})`,
        topStatus: "ACTIVE",
        topDate: formatYMD(periodEnd),
        billingPeriodStart: formatYMD(currentPeriodStart),
        billingPeriodEnd: formatYMD(periodEnd),
        isAutoGenerated: true,
      });

      currentPeriodStart = new Date(
        periodEnd.getFullYear(),
        periodEnd.getMonth(),
        periodEnd.getDate() + 1
      );
      step++;
    }

    const mergedList = [...paidSteps, ...newUnpaidList];
    formik.setFieldValue("topList", mergedList);
    setShowTopDates(true);

    const newSum = mergedList.reduce((acc, curr) => acc + (curr.topValues || 0), 0);
    handleTotalWorkValueChange(newSum);

    showToast({
      description: `Synchronized subscription schedule (${paidSteps.length} paid preserved, ${newUnpaidList.length} unpaid generated, total ${formatIDR(newSum)})`,
      statusToast: "success",
    });
  };

  // TOP schedule helpers
  const handleAddTopStep = () => {
    const nextOrder = (formik.values.topList?.length || 0) + 1;
    formik.setFieldValue("topList", [
      ...(formik.values.topList || []),
      { stepOrder: nextOrder, topValues: 0, topDate: "", topDescriptions: "", topStatus: "ACTIVE" },
    ]);
  };

  const handleRemoveTopStep = (index: number) => {
    const updated = [...(formik.values.topList || [])];
    updated.splice(index, 1);
    formik.setFieldValue("topList", updated);
  };

  // Real-time Financial Reconciliation & Anomaly Calculations
  const totalWorkValue = formik.values.workValue || 0;

  // Paid TOPs sum (Locked actual disbursements)
  const paidTopAmount = (formik.values.topList || [])
    .filter((t) => t.topStatus && t.topStatus.toUpperCase() === "PAID")
    .reduce((acc, curr) => acc + (curr.topValues || 0), 0);

  const paidPercentage =
    totalWorkValue > 0 ? parseFloat(((paidTopAmount / totalWorkValue) * 100).toFixed(1)) : 0;

  // Remaining available contract budget
  const remainingBudget = totalWorkValue - paidTopAmount;

  // Unpaid / Future Scheduled TOPs
  const unpaidTopList = (formik.values.topList || []).filter(
    (t) => !t.topStatus || t.topStatus.toUpperCase() !== "PAID"
  );
  const unpaidTopAmount = unpaidTopList.reduce((acc, curr) => acc + (curr.topValues || 0), 0);

  // Total TOP Schedule sum (Paid + Unpaid)
  const totalTopValues = (formik.values.topList || []).reduce((acc, curr) => acc + (curr.topValues || 0), 0);

  // Anomaly flags
  const isDeficitAnomaly = totalWorkValue < paidTopAmount; // CRITICAL: Work value less than already paid
  const isScheduleMismatch = totalTopValues !== totalWorkValue;
  const isTopMatch = totalTopValues === totalWorkValue;
  const variance = totalTopValues - totalWorkValue;

  // Synchronize Work Value to Total TOPs (ideal for subscription price adjustments or milestone additions)
  const handleSyncWorkValueToTopSum = () => {
    handleTotalWorkValueChange(totalTopValues);
    showToast({
      description: `Contract Total Work Value synchronized to TOP sum (${formatIDR(totalTopValues)})`,
      statusToast: "success",
    });
  };

  // Auto-Balance Remaining Unpaid Milestones (distributes available budget across unpaid steps)
  const handleAutoBalanceRemainingTops = () => {
    if (isDeficitAnomaly) {
      showToast({
        description: "Cannot balance steps: Total Work Value is lower than already paid amount.",
        statusToast: "error",
      });
      return;
    }
    const unpaidIndices: number[] = [];
    (formik.values.topList || []).forEach((t, idx) => {
      if (!t.topStatus || t.topStatus.toUpperCase() !== "PAID") {
        unpaidIndices.push(idx);
      }
    });

    if (unpaidIndices.length === 0) {
      showToast({
        description: "No unpaid steps available to balance.",
        statusToast: "warning",
      });
      return;
    }

    const availableBudget = Math.max(0, remainingBudget);
    const count = unpaidIndices.length;
    const baseAmount = Math.floor(availableBudget / count);
    const remainder = availableBudget - baseAmount * count;

    const updated = [...(formik.values.topList || [])];
    unpaidIndices.forEach((idx, i) => {
      updated[idx] = {
        ...updated[idx],
        topValues: i === count - 1 ? baseAmount + remainder : baseAmount,
      };
    });

    formik.setFieldValue("topList", updated);
    showToast({
      description: `Remaining budget of ${formatIDR(availableBudget)} evenly distributed across ${count} unpaid milestone(s).`,
      statusToast: "success",
    });
  };

  const handleExecuteSave = async () => {
    if (!tokenData) return;
    setIsSubmitting(true);

    const cleanDate = (val?: string) => (val && val.trim() !== "" ? val : undefined);

    const sanitizedPayload: VendorContractInsertPayload = {
      ...formik.values,
      worksStartDate: cleanDate(formik.values.worksStartDate),
      worksEndDate: cleanDate(formik.values.worksEndDate),
      warrantyStartDate: cleanDate(formik.values.warrantyStartDate),
      warrantyEndDate: cleanDate(formik.values.warrantyEndDate),
      maintenanceStartDate: cleanDate(formik.values.maintenanceStartDate),
      maintenanceEndDate: cleanDate(formik.values.maintenanceEndDate),
      performanceGuaranteeStartDate: cleanDate(formik.values.performanceGuaranteeStartDate),
      performanceGuaranteeEndDate: cleanDate(formik.values.performanceGuaranteeEndDate),
      maintenanceWarrantyStartDate: cleanDate(formik.values.maintenanceWarrantyStartDate),
      maintenanceWarrantyEndDate: cleanDate(formik.values.maintenanceWarrantyEndDate),
      performanceGuaranteeValues: formik.values.performanceGuaranteeValues || 0,
      maintenanceWarrantyValues: formik.values.maintenanceWarrantyValues || 0,
      cavexValues: formik.values.cavexValues || 0,
      capexPercentage: formik.values.capexPercentage || 0,
      ovexValues: formik.values.ovexValues || 0,
      ovexPercentage: formik.values.ovexPercentage || 0,
      contractBillingType: formik.values.contractBillingType || "MILESTONE",
      subscriptionPeriodValue: formik.values.subscriptionPeriodValue || undefined,
      subscriptionAutoRenew: !!formik.values.subscriptionAutoRenew,
      topList: (formik.values.topList || []).map((t) => ({
        id: t.id,
        stepOrder: t.stepOrder,
        topValues: t.topValues || 0,
        topDescriptions: t.topDescriptions,
        topStatus: t.topStatus,
        topDate: cleanDate(t.topDate),
        billingPeriodStart: cleanDate(t.billingPeriodStart),
        billingPeriodEnd: cleanDate(t.billingPeriodEnd),
        isAutoGenerated: !!t.isAutoGenerated,
      })),
    };

    const res = await InsertContract(sanitizedPayload, tokenData);
    if (res?.statusCode === RES_CODE_OK) {
      showToast({ description: "Contract updated successfully! Audit history snapshot recorded.", statusToast: "success" });
      confirmModal.onClose();
      onRefreshData();
    } else {
      showToast({ description: res?.message || "Failed to update contract", statusToast: "error" });
    }
    setIsSubmitting(false);
  };

  return (
    <VStack spacing={6} align="stretch">
      {/* SECTION 1: Vendor Partner (Readonly) & Basic Contract Info */}
      <Card rounded="2xl" shadow="sm" border="1px" borderColor={colorMode === "light" ? "gray.200" : "gray.700"}>
        <CardHeader bg={colorMode === "light" ? "gray.50" : "gray.900"} py={4} roundedTop="2xl">
          <HStack spacing={3}>
            <Box w={9} h={9} bg="secondary.500" rounded="lg" display="flex" alignItems="center" justifyContent="center" color="white">
              <Icon as={FiBriefcase} boxSize={5} />
            </Box>
            <VStack align="start" spacing={0}>
              <Heading size="md">1. Corporate Vendor & Project Header (Locked)</Heading>
              <Text fontSize="xs" color="gray.500">Vendor entity and Procurement Project are locked to maintain contract audit integrity</Text>
            </VStack>
          </HStack>
        </CardHeader>

        <CardBody p={6}>
          <VStack spacing={5} align="stretch">
            {/* Corporate Procurement Project Locked Card */}
            <FormControl>
              <Flex justify="space-between" align="center" mb={1}>
                <FormLabel fontSize="sm" fontWeight="bold" m={0}>
                  Corporate Procurement Project
                </FormLabel>
                {selectedProject && (
                  <Badge colorScheme="purple" fontSize="2xs" px={2} py={0.5} rounded="md">
                    Linked to Project
                  </Badge>
                )}
              </Flex>
              {selectedProject ? (
                <Box
                  p={4}
                  rounded="xl"
                  border="1px"
                  borderColor={colorMode === "light" ? "purple.300" : "purple.700"}
                  bg={colorMode === "light" ? "purple.50/40" : "gray.800"}
                >
                  <Flex justify="space-between" align="center" wrap="wrap" gap={3}>
                    <HStack spacing={3}>
                      <Box
                        w={10}
                        h={10}
                        bg="purple.500"
                        rounded="xl"
                        display="flex"
                        alignItems="center"
                        justifyContent="center"
                        color="white"
                      >
                        <Icon as={FiBriefcase} boxSize={5} />
                      </Box>
                      <VStack align="start" spacing={0.5}>
                        <HStack spacing={2} wrap="wrap">
                          <Badge colorScheme="purple">
                            {selectedProject.projectCode || "NO-CODE"}
                          </Badge>
                          <Badge colorScheme="blue">
                            PROCUREMENT
                          </Badge>
                          {selectedProject.sdlcStageName && (
                            <Badge colorScheme="teal" variant="outline">
                              {selectedProject.sdlcStageName}
                            </Badge>
                          )}
                        </HStack>
                        <Text fontSize="md" fontWeight="bold">
                          {selectedProject.projectName}
                        </Text>
                        <Text fontSize="xs" color="gray.500">
                          {selectedProject.proOwnerDivisionName || "Division not set"} • {selectedProject.proOwnerDirectorateName || "Directorate not set"}
                        </Text>
                      </VStack>
                    </HStack>

                    <HStack
                      spacing={1.5}
                      fontSize="xs"
                      color="gray.500"
                      bg={colorMode === "light" ? "white" : "gray.700"}
                      px={3}
                      py={1.5}
                      rounded="lg"
                      border="1px"
                      borderColor={colorMode === "light" ? "purple.200" : "gray.600"}
                    >
                      <Icon as={FiLock} color="purple.500" />
                      <Text fontWeight="600">Locked Project Entity</Text>
                    </HStack>
                  </Flex>
                </Box>
              ) : (
                <Box
                  p={4}
                  rounded="xl"
                  border="1px"
                  borderColor={colorMode === "light" ? "gray.200" : "gray.700"}
                  bg={colorMode === "light" ? "gray.50" : "gray.800"}
                >
                  <HStack spacing={2} color="gray.500">
                    <Icon as={FiLock} />
                    <Text fontSize="xs" fontWeight="semibold">
                      No Corporate Procurement Project linked to this contract (Locked)
                    </Text>
                  </HStack>
                </Box>
              )}
            </FormControl>

            {/* Vendor Partner Readonly Banner */}
            <Box p={4} rounded="xl" border="1px" borderColor="purple.300" bg={colorMode === "light" ? "purple.50/40" : "gray.700"}>
              <Flex justify="space-between" align="center" wrap="wrap" gap={3}>
                <HStack spacing={3}>
                  <Box w={10} h={10} bg="purple.500" rounded="xl" display="flex" alignItems="center" justifyContent="center" color="white">
                    <Icon as={FiUserCheck} boxSize={5} />
                  </Box>
                  <VStack align="start" spacing={0}>
                    <HStack spacing={2}>
                      <Badge colorScheme="purple" fontSize="2xs">Locked Vendor Partner</Badge>
                      <Badge colorScheme="blue" fontSize="2xs">{contract.vendorCode || "VEN-CODE"}</Badge>
                    </HStack>
                    <Text fontSize="md" fontWeight="bold">
                      {contract.vendorName || contract.vendor?.vendorName || "Vendor Company"}
                    </Text>
                  </VStack>
                </HStack>

                <HStack spacing={1.5} fontSize="xs" color="gray.500" bg={colorMode === "light" ? "white" : "gray.800"} px={3} py={1.5} rounded="lg" border="1px" borderColor="gray.200">
                  <Icon as={FiLock} color="purple.500" />
                  <Text fontWeight="600">Vendor Entity Cannot Be Changed</Text>
                </HStack>
              </Flex>
            </Box>

            {/* Basic Contract Fields */}
            <Grid templateColumns={{ base: "1fr", md: "1fr 1fr" }} gap={4}>
              <GridItem>
                <FormControl isReadOnly isDisabled>
                  <FormLabel fontSize="xs" fontWeight="bold">
                    <HStack spacing={1}>
                      <Text>SPK / Corporate Ref Number *</Text>
                      <Icon as={FiLock} color="gray.400" boxSize={3} />
                    </HStack>
                  </FormLabel>
                  <Input
                    size="sm"
                    rounded="md"
                    name="corpNumber"
                    value={formik.values.corpNumber}
                    isReadOnly
                    isDisabled
                    bg={colorMode === "light" ? "gray.100" : "gray.700"}
                    cursor="not-allowed"
                  />
                </FormControl>
              </GridItem>

              <GridItem>
                <FormControl isInvalid={!!formik.errors.corpName && formik.touched.corpName}>
                  <FormLabel fontSize="xs" fontWeight="bold">Project / Contract Title *</FormLabel>
                  <Input
                    size="sm"
                    rounded="md"
                    placeholder="e.g. Enterprise Solution Development 2026"
                    name="corpName"
                    value={formik.values.corpName}
                    onChange={formik.handleChange}
                  />
                </FormControl>
              </GridItem>

              <GridItem>
                <FormControl isReadOnly isDisabled>
                  <FormLabel fontSize="xs" fontWeight="bold">
                    <HStack spacing={1}>
                      <Text>Contract Official Number *</Text>
                      <Icon as={FiLock} color="gray.400" boxSize={3} />
                    </HStack>
                  </FormLabel>
                  <Input
                    size="sm"
                    rounded="md"
                    name="contractNumber"
                    value={formik.values.contractNumber}
                    isReadOnly
                    isDisabled
                    bg={colorMode === "light" ? "gray.100" : "gray.700"}
                    cursor="not-allowed"
                  />
                </FormControl>
              </GridItem>

              <GridItem>
                <FormControl isInvalid={!!formik.errors.contractDate && formik.touched.contractDate}>
                  <FormLabel fontSize="xs" fontWeight="bold">Contract Signing Date *</FormLabel>
                  <Input
                    size="sm"
                    type="date"
                    rounded="md"
                    name="contractDate"
                    value={formik.values.contractDate}
                    onChange={formik.handleChange}
                  />
                </FormControl>
              </GridItem>
            </Grid>

            {/* Contract Billing Model & Recurring Setup */}
            <Box p={4} rounded="xl" border="1px solid" borderColor={colorMode === "light" ? "teal.200" : "teal.800"} bg={colorMode === "light" ? "teal.50/30" : "gray.800"}>
              <VStack align="stretch" spacing={3}>
                <Flex justify="space-between" align="center" wrap="wrap" gap={2}>
                  <HStack spacing={2}>
                    <Icon as={FiRepeat} color="teal.500" />
                    <Text fontSize="xs" fontWeight="bold">Contract Billing Model & Schedule Type</Text>
                  </HStack>
                  <Badge colorScheme={formik.values.contractBillingType === "MILESTONE" ? "blue" : "purple"} fontSize="2xs" px={2} py={0.5} rounded="md">
                    {formik.values.contractBillingType || "MILESTONE"}
                  </Badge>
                </Flex>

                <Grid templateColumns={{ base: "1fr", md: formik.values.contractBillingType !== "MILESTONE" ? "repeat(3, 1fr)" : "1fr" }} gap={4} alignItems="center">
                  <GridItem>
                    <FormControl isReadOnly isDisabled>
                      <Flex justify="space-between" align="center" mb={1}>
                        <FormLabel fontSize="2xs" fontWeight="bold" m={0}>
                          Billing Model Type
                        </FormLabel>
                        <Badge colorScheme="gray" fontSize="3xs">
                          <HStack spacing={1}>
                            <Icon as={FiLock} />
                            <Text>Locked Structure</Text>
                          </HStack>
                        </Badge>
                      </Flex>
                      <ChakraSelect
                        size="sm"
                        rounded="md"
                        name="contractBillingType"
                        value={formik.values.contractBillingType || "MILESTONE"}
                        isDisabled
                        isReadOnly
                        bg={colorMode === "light" ? "gray.100" : "gray.700"}
                        cursor="not-allowed"
                      >
                        <option value="MILESTONE">Milestone / Deliverable Progress TOP</option>
                        <option value="SUBSCRIPTION_MONTHLY">Monthly Subscription</option>
                        <option value="SUBSCRIPTION_QUARTERLY">Quarterly Subscription (3 Months)</option>
                        <option value="SUBSCRIPTION_SEMI_ANNUAL">Semi-Annual Subscription (6 Months)</option>
                        <option value="SUBSCRIPTION_ANNUAL">Annual Subscription (Yearly)</option>
                        <option value="CUSTOM_RECURRING">Custom Recurring Period</option>
                      </ChakraSelect>
                    </FormControl>
                  </GridItem>

                  {formik.values.contractBillingType !== "MILESTONE" && (
                    <>
                      <GridItem>
                        <FormControl>
                          <Flex justify="space-between" align="center" mb={1}>
                            <FormLabel fontSize="2xs" fontWeight="bold" m={0}>
                              Periodic Rate (Rp. per cycle) *
                            </FormLabel>
                            <Badge colorScheme="purple" fontSize="3xs">
                              Auto-adjusts Unpaid TOPs
                            </Badge>
                          </Flex>
                          <CurrencyInput
                            size="sm"
                            rounded="md"
                            name="subscriptionPeriodValue"
                            value={formik.values.subscriptionPeriodValue || 0}
                            onChange={(_, val) => handlePeriodicRateChange(val)}
                          />
                        </FormControl>
                      </GridItem>

                      <GridItem>
                        <FormControl display="flex" alignItems="center" pt={4}>
                          <Switch
                            id="edit-subscriptionAutoRenew"
                            colorScheme="teal"
                            isChecked={!!formik.values.subscriptionAutoRenew}
                            onChange={(e) => formik.setFieldValue("subscriptionAutoRenew", e.target.checked)}
                            mr={2}
                          />
                          <FormLabel htmlFor="edit-subscriptionAutoRenew" mb="0" fontSize="xs" fontWeight="bold" cursor="pointer">
                            Auto-Renew Contract
                          </FormLabel>
                        </FormControl>
                      </GridItem>
                    </>
                  )}
                </Grid>
              </VStack>
            </Box>
          </VStack>
        </CardBody>
      </Card>

      {/* SECTION 2: Monetary Work Value & CAPEX / OPEX Allocation */}
      <Card rounded="2xl" shadow="sm" border="1px" borderColor={colorMode === "light" ? "gray.200" : "gray.700"}>
        <CardHeader bg={colorMode === "light" ? "gray.50" : "gray.900"} py={4} roundedTop="2xl">
          <HStack spacing={3}>
            <Box w={9} h={9} bg="secondary.500" rounded="lg" display="flex" alignItems="center" justifyContent="center" color="white">
              <Icon as={FiDollarSign} boxSize={5} />
            </Box>
            <VStack align="start" spacing={0}>
              <Heading size="md">2. Contract Monetary Value & CAPEX / OPEX Allocation</Heading>
              <Text fontSize="xs" color="gray.500">Configure total work value (IDR) and financial category breakdown</Text>
            </VStack>
          </HStack>
        </CardHeader>

        <CardBody p={6}>
          <VStack spacing={6} align="stretch">
            {/* Total Work Value */}
            <FormControl isInvalid={!!formik.errors.workValue && formik.touched.workValue}>
              <FormLabel fontSize="xs" fontWeight="bold">Total Contract Work Value (Rp.) *</FormLabel>
              <CurrencyInput
                size="md"
                rounded="md"
                name="workValue"
                value={formik.values.workValue}
                onChange={(_, val) => handleTotalWorkValueChange(val)}
              />
            </FormControl>

            {/* CAPEX Allocation */}
            <Box p={4} rounded="xl" border="1px" borderColor={colorMode === "light" ? "gray.200" : "gray.700"} bg={colorMode === "light" ? "blue.50/30" : "gray.800"}>
              <VStack spacing={3} align="stretch">
                <Flex justify="space-between" align="center">
                  <Text fontSize="xs" fontWeight="bold" color="blue.600">CAPEX (Capital Expenditure)</Text>
                  <Badge colorScheme="blue" fontSize="2xs">{formik.values.capexPercentage || 0}%</Badge>
                </Flex>

                <Grid templateColumns={{ base: "1fr", md: "1fr 140px" }} gap={3} alignItems="center">
                  <GridItem>
                    <FormControl>
                      <FormLabel fontSize="2xs">CAPEX Amount (Rp.)</FormLabel>
                      <CurrencyInput
                        size="sm"
                        rounded="md"
                        name="cavexValues"
                        value={formik.values.cavexValues || 0}
                        onChange={(_, val) => handleCapexValueChange(val)}
                      />
                    </FormControl>
                  </GridItem>

                  <GridItem>
                    <FormControl>
                      <FormLabel fontSize="2xs">CAPEX %</FormLabel>
                      <NumberInput
                        size="sm"
                        min={0}
                        max={100}
                        precision={1}
                        value={formik.values.capexPercentage || 0}
                        onChange={(_, val) => handleCapexPercentageChange(isNaN(val) ? 0 : val)}
                      >
                        <NumberInputField rounded="md" />
                        <NumberInputStepper>
                          <NumberIncrementStepper />
                          <NumberDecrementStepper />
                        </NumberInputStepper>
                      </NumberInput>
                    </FormControl>
                  </GridItem>
                </Grid>

                <Slider
                  value={formik.values.capexPercentage || 0}
                  min={0}
                  max={100}
                  step={0.5}
                  colorScheme="blue"
                  onChange={(val) => handleCapexPercentageChange(val)}
                >
                  <SliderTrack rounded="full">
                    <SliderFilledTrack />
                  </SliderTrack>
                  <SliderThumb />
                </Slider>
              </VStack>
            </Box>

            {/* OPEX Allocation */}
            <Box p={4} rounded="xl" border="1px" borderColor={colorMode === "light" ? "gray.200" : "gray.700"} bg={colorMode === "light" ? "purple.50/30" : "gray.800"}>
              <VStack spacing={3} align="stretch">
                <Flex justify="space-between" align="center">
                  <Text fontSize="xs" fontWeight="bold" color="purple.600">OPEX (Operational Expenditure)</Text>
                  <Badge colorScheme="purple" fontSize="2xs">{formik.values.ovexPercentage || 0}%</Badge>
                </Flex>

                <Grid templateColumns={{ base: "1fr", md: "1fr 140px" }} gap={3} alignItems="center">
                  <GridItem>
                    <FormControl>
                      <FormLabel fontSize="2xs">OPEX Amount (Rp.)</FormLabel>
                      <CurrencyInput
                        size="sm"
                        rounded="md"
                        name="ovexValues"
                        value={formik.values.ovexValues || 0}
                        onChange={(_, val) => handleOvexValueChange(val)}
                      />
                    </FormControl>
                  </GridItem>

                  <GridItem>
                    <FormControl>
                      <FormLabel fontSize="2xs">OPEX %</FormLabel>
                      <NumberInput
                        size="sm"
                        min={0}
                        max={100}
                        precision={1}
                        value={formik.values.ovexPercentage || 0}
                        onChange={(_, val) => handleOvexPercentageChange(isNaN(val) ? 0 : val)}
                      >
                        <NumberInputField rounded="md" />
                        <NumberInputStepper>
                          <NumberIncrementStepper />
                          <NumberDecrementStepper />
                        </NumberInputStepper>
                      </NumberInput>
                    </FormControl>
                  </GridItem>
                </Grid>
              </VStack>
            </Box>
          </VStack>
        </CardBody>
      </Card>

      {/* SECTION 3: Execution Timelines & SLA Periods */}
      <Card rounded="2xl" shadow="sm" border="1px" borderColor={colorMode === "light" ? "gray.200" : "gray.700"}>
        <CardHeader bg={colorMode === "light" ? "gray.50" : "gray.900"} py={4} roundedTop="2xl">
          <HStack spacing={3}>
            <Box w={9} h={9} bg="blue.500" rounded="lg" display="flex" alignItems="center" justifyContent="center" color="white">
              <Icon as={FiCalendar} boxSize={5} />
            </Box>
            <VStack align="start" spacing={0}>
              <Heading size="md">3. Execution Timelines & SLA Periods</Heading>
              <Text fontSize="xs" color="gray.500">Contract validity range, project execution works, and warranty/maintenance SLAs</Text>
            </VStack>
          </HStack>
        </CardHeader>

        <CardBody p={6}>
          <VStack spacing={5} align="stretch">
            {/* Contract Validity */}
            <Heading size="xs" color="gray.600" textTransform="uppercase">Contract Validity Period</Heading>
            <Grid templateColumns={{ base: "1fr", md: "1fr 1fr" }} gap={4}>
              <GridItem>
                <FormControl isInvalid={!!formik.errors.contractStartDate && formik.touched.contractStartDate}>
                  <FormLabel fontSize="xs" fontWeight="bold">Contract Start Date *</FormLabel>
                  <Input
                    size="sm"
                    type="date"
                    rounded="md"
                    name="contractStartDate"
                    value={formik.values.contractStartDate ? formik.values.contractStartDate.split("T")[0] : ""}
                    onChange={(e) => {
                      const val = e.target.value;
                      formik.setFieldValue("contractStartDate", val);
                      if (formik.values.contractBillingType !== "MILESTONE" && formik.values.contractEndDate) {
                        handleQuickGenerateSubscriptionTop(undefined, val, formik.values.contractEndDate);
                      }
                    }}
                  />
                  <FormErrorMessage>{formik.errors.contractStartDate}</FormErrorMessage>
                </FormControl>
              </GridItem>
              <GridItem>
                <FormControl isInvalid={!!formik.errors.contractEndDate && formik.touched.contractEndDate}>
                  <FormLabel fontSize="xs" fontWeight="bold">Contract End Date *</FormLabel>
                  <Input
                    size="sm"
                    type="date"
                    rounded="md"
                    name="contractEndDate"
                    value={formik.values.contractEndDate ? formik.values.contractEndDate.split("T")[0] : ""}
                    onChange={(e) => {
                      const val = e.target.value;
                      formik.setFieldValue("contractEndDate", val);
                      if (formik.values.contractBillingType !== "MILESTONE" && formik.values.contractStartDate) {
                        handleQuickGenerateSubscriptionTop(undefined, formik.values.contractStartDate, val);
                      }
                    }}
                  />
                  <FormErrorMessage>{formik.errors.contractEndDate}</FormErrorMessage>
                </FormControl>
              </GridItem>
            </Grid>

            {/* Works Execution */}
            <Heading size="xs" color="gray.600" textTransform="uppercase">Project Works Execution Period</Heading>
            <Grid templateColumns={{ base: "1fr", md: "1fr 1fr" }} gap={4}>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Works Start Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("worksStartDate")} />
                </FormControl>
              </GridItem>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Works End Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("worksEndDate")} />
                </FormControl>
              </GridItem>
            </Grid>

            {/* Warranty & Maintenance SLAs */}
            <Heading size="xs" color="gray.600" textTransform="uppercase">Warranty & Maintenance SLA Periods</Heading>
            <Grid templateColumns={{ base: "1fr", md: "1fr 1fr" }} gap={4}>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Warranty SLA Start Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("warrantyStartDate")} />
                </FormControl>
              </GridItem>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Warranty SLA End Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("warrantyEndDate")} />
                </FormControl>
              </GridItem>

              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Maintenance SLA Start Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("maintenanceStartDate")} />
                </FormControl>
              </GridItem>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Maintenance SLA End Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("maintenanceEndDate")} />
                </FormControl>
              </GridItem>
            </Grid>
          </VStack>
        </CardBody>
      </Card>

      {/* SECTION 4: Financial Guarantees & Bonds */}
      <Card rounded="2xl" shadow="sm" border="1px" borderColor={colorMode === "light" ? "gray.200" : "gray.700"}>
        <CardHeader bg={colorMode === "light" ? "gray.50" : "gray.900"} py={4} roundedTop="2xl">
          <HStack spacing={3}>
            <Box w={9} h={9} bg="purple.500" rounded="lg" display="flex" alignItems="center" justifyContent="center" color="white">
              <Icon as={FiShield} boxSize={5} />
            </Box>
            <VStack align="start" spacing={0}>
              <Heading size="md">4. Financial Guarantees & Bonds</Heading>
              <Text fontSize="xs" color="gray.500">Configure Performance Bond and Maintenance Warranty Bond values & validity dates</Text>
            </VStack>
          </HStack>
        </CardHeader>

        <CardBody p={6}>
          <VStack spacing={6} align="stretch">
            {/* Maintenance Warranty Bond */}
            <Heading size="xs" color="gray.600" textTransform="uppercase">Maintenance Warranty Bond (Jaminan Pemeliharaan)</Heading>
            <Grid templateColumns={{ base: "1fr", md: "repeat(3, 1fr)" }} gap={4}>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Warranty Bond Value (Rp.)</FormLabel>
                  <CurrencyInput
                    size="sm"
                    rounded="md"
                    name="maintenanceWarrantyValues"
                    value={formik.values.maintenanceWarrantyValues || 0}
                    onChange={formik.setFieldValue}
                  />
                </FormControl>
              </GridItem>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Warranty Bond Start Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("maintenanceWarrantyStartDate")} />
                </FormControl>
              </GridItem>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Warranty Bond End Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("maintenanceWarrantyEndDate")} />
                </FormControl>
              </GridItem>
            </Grid>

            <Divider />

            {/* Performance Guarantee Bond */}
            <Heading size="xs" color="gray.600" textTransform="uppercase">Performance Bond (Jaminan Pelaksanaan)</Heading>
            <Grid templateColumns={{ base: "1fr", md: "repeat(3, 1fr)" }} gap={4}>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Performance Bond Value (Rp.)</FormLabel>
                  <CurrencyInput
                    size="sm"
                    rounded="md"
                    name="performanceGuaranteeValues"
                    value={formik.values.performanceGuaranteeValues || 0}
                    onChange={formik.setFieldValue}
                  />
                </FormControl>
              </GridItem>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Performance Bond Start Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("performanceGuaranteeStartDate")} />
                </FormControl>
              </GridItem>
              <GridItem>
                <FormControl>
                  <FormLabel fontSize="xs" fontWeight="bold">Performance Bond End Date</FormLabel>
                  <Input size="sm" type="date" rounded="md" {...formik.getFieldProps("performanceGuaranteeEndDate")} />
                </FormControl>
              </GridItem>
            </Grid>
          </VStack>
        </CardBody>
      </Card>

      {/* SECTION 5: Terms of Payment (TOP) Schedule */}
      <Card rounded="2xl" shadow="sm" border="1px" borderColor={colorMode === "light" ? "gray.200" : "gray.700"}>
        <CardHeader bg={colorMode === "light" ? "gray.50" : "gray.900"} py={4} roundedTop="2xl">
          <Flex justify="space-between" align="center" wrap="wrap" gap={3}>
            <HStack spacing={3}>
              <Box w={9} h={9} bg="teal.500" rounded="lg" display="flex" alignItems="center" justifyContent="center" color="white">
                <Icon as={FiDollarSign} boxSize={5} />
              </Box>
              <VStack align="start" spacing={0}>
                <HStack spacing={2}>
                  <Heading size="md">5. Terms of Payment (TOP) Schedule</Heading>
                  {formik.values.contractBillingType !== "MILESTONE" && (
                    <Badge colorScheme="purple" fontSize="2xs" px={2} py={0.5} rounded="md">
                      {formik.values.contractBillingType}
                    </Badge>
                  )}
                </HStack>
                <Text fontSize="xs" color="gray.500">Define payment milestones, recurring billing periods, and optional due dates</Text>
              </VStack>
            </HStack>

            <HStack spacing={3} wrap="wrap">
              {formik.values.contractBillingType !== "MILESTONE" && (
                <Button
                  size="sm"
                  colorScheme="purple"
                  variant="solid"
                  leftIcon={<FiRepeat />}
                  onClick={() => handleQuickGenerateSubscriptionTop()}
                  title="Re-align unpaid subscription billing cycles with current contract dates & periodic rate (preserves PAID steps)"
                >
                  Re-align Schedule with Dates
                </Button>
              )}

              <FormControl display="flex" alignItems="center" w="auto">
                <FormLabel htmlFor="toggle-edit-top-dates" mb="0" fontSize="xs" fontWeight="bold" color="gray.600" cursor="pointer" mr={2}>
                  Include Due Dates
                </FormLabel>
                <Switch
                  id="toggle-edit-top-dates"
                  size="sm"
                  colorScheme="teal"
                  isChecked={showTopDates}
                  onChange={(e) => setShowTopDates(e.target.checked)}
                />
              </FormControl>

              <Button
                size="sm"
                colorScheme="teal"
                variant="outline"
                leftIcon={<FiSliders />}
                isDisabled={isPaymentRunning}
                onClick={topAutoAdjustModal.onOpen}
                title={
                  isPaymentRunning
                    ? "Cannot auto-adjust schedule while payment execution is in progress"
                    : "Auto calculate and adjust TOP payment schedule"
                }
              >
                Auto Schedule
              </Button>

              <Button size="sm" colorScheme="teal" leftIcon={<FiPlus />} onClick={handleAddTopStep}>
                Add Payment Step
              </Button>
            </HStack>
          </Flex>
        </CardHeader>

        <CardBody p={6}>
          <VStack spacing={4} align="stretch">
            {/* Payment Running Security Alert Banner */}
            {isPaymentRunning && (
              <Alert status="info" rounded="xl" variant="left-accent">
                <AlertIcon />
                <Box flex={1}>
                  <HStack spacing={2} mb={0.5}>
                    <Icon as={FiLock} color="blue.500" />
                    <Text fontSize="xs" fontWeight="bold">
                      Payment Realization In-Progress ({paidTopCount} Paid, {inProgressTopCount} Active Steps)
                    </Text>
                  </HStack>
                  <Text fontSize="2xs" color="gray.600">
                    Payment milestones that are already PAID or under verification are locked to preserve financial integrity and BAST/Invoice archives. You can still add or modify upcoming unpaid milestones.
                  </Text>
                </Box>
              </Alert>
            )}

            {/* Real-time Financial Reconciliation Summary Card */}
            <Card
              p={4}
              rounded="xl"
              bg={colorMode === "light" ? "gray.50" : "gray.900"}
              border="1px"
              borderColor={
                isDeficitAnomaly
                  ? "red.300"
                  : isScheduleMismatch
                  ? "orange.300"
                  : colorMode === "light"
                  ? "gray.200"
                  : "gray.700"
              }
            >
              <Grid templateColumns={{ base: "1fr", sm: "repeat(2, 1fr)", md: "repeat(4, 1fr)" }} gap={4}>
                {/* 1. Total Work Value */}
                <Box>
                  <Text fontSize="2xs" fontWeight="bold" color="gray.500" textTransform="uppercase">
                    Total Contract Value
                  </Text>
                  <Text fontSize="md" fontWeight="extrabold" color="teal.500">
                    {formatIDR(totalWorkValue)}
                  </Text>
                  <Badge colorScheme="teal" fontSize="3xs" rounded="md" px={1.5}>
                    {formik.values.contractBillingType || "MILESTONE"}
                  </Badge>
                </Box>

                {/* 2. Paid / Realized */}
                <Box>
                  <Text fontSize="2xs" fontWeight="bold" color="gray.500" textTransform="uppercase">
                    Realized / Disbursed (Paid)
                  </Text>
                  <HStack spacing={1.5} align="baseline">
                    <Text fontSize="md" fontWeight="extrabold" color={paidTopAmount > 0 ? "green.500" : "gray.600"}>
                      {formatIDR(paidTopAmount)}
                    </Text>
                    {paidTopAmount > 0 && (
                      <Badge colorScheme="green" fontSize="3xs" rounded="md" px={1}>
                        {paidPercentage}%
                      </Badge>
                    )}
                  </HStack>
                  <Text fontSize="3xs" color="gray.500">
                    {paidTopCount} of {(formik.values.topList || []).length} steps paid (Locked)
                  </Text>
                </Box>

                {/* 3. Available Remaining Budget */}
                <Box>
                  <Text fontSize="2xs" fontWeight="bold" color="gray.500" textTransform="uppercase">
                    Available Remaining Budget
                  </Text>
                  <Text
                    fontSize="md"
                    fontWeight="extrabold"
                    color={remainingBudget < 0 ? "red.500" : "blue.500"}
                  >
                    {formatIDR(remainingBudget)}
                  </Text>
                  <Text fontSize="3xs" color="gray.500">
                    Work Value - Disbursed Amount
                  </Text>
                </Box>

                {/* 4. Scheduled TOP Milestones */}
                <Box>
                  <Text fontSize="2xs" fontWeight="bold" color="gray.500" textTransform="uppercase">
                    Scheduled Milestones
                  </Text>
                  <Text
                    fontSize="md"
                    fontWeight="extrabold"
                    color={isTopMatch ? "green.500" : isDeficitAnomaly ? "red.500" : "orange.500"}
                  >
                    {formatIDR(totalTopValues)}
                  </Text>
                  <Badge
                    colorScheme={isTopMatch ? "green" : isDeficitAnomaly ? "red" : "orange"}
                    fontSize="3xs"
                    rounded="md"
                    px={1.5}
                  >
                    {isTopMatch ? "Reconciled ✓" : isDeficitAnomaly ? "Deficit Anomaly ✗" : "Mismatch Variance ✗"}
                  </Badge>
                </Box>
              </Grid>
            </Card>

            {/* Dynamic Anomaly Alert Banners */}
            {isDeficitAnomaly ? (
              <Alert status="error" rounded="xl" variant="left-accent">
                <AlertIcon />
                <Box flex={1}>
                  <HStack spacing={2} mb={0.5}>
                    <Icon as={FiAlertCircle} color="red.500" />
                    <Text fontSize="xs" fontWeight="bold">
                      Critical Financial Anomaly: Total Work Value Underflow
                    </Text>
                  </HStack>
                  <Text fontSize="2xs" color="gray.600" mb={2}>
                    Total Contract Work Value ({formatIDR(totalWorkValue)}) cannot be less than the amount already disbursed to the vendor ({formatIDR(paidTopAmount)}). Deficit variance: {formatIDR(Math.abs(remainingBudget))}. Please adjust Total Work Value to at least {formatIDR(paidTopAmount)}.
                  </Text>
                  <Button
                    size="xs"
                    colorScheme="red"
                    variant="solid"
                    onClick={() => handleTotalWorkValueChange(paidTopAmount + unpaidTopAmount)}
                  >
                    Fix: Set Work Value to {formatIDR(paidTopAmount + unpaidTopAmount)}
                  </Button>
                </Box>
              </Alert>
            ) : isScheduleMismatch ? (
              <Alert status="warning" rounded="xl" variant="left-accent">
                <AlertIcon />
                <Box flex={1}>
                  <HStack spacing={2} mb={0.5}>
                    <Icon as={FiAlertTriangle} color="orange.500" />
                    <Text fontSize="xs" fontWeight="bold">
                      TOP Schedule & Contract Value Mismatch
                    </Text>
                  </HStack>
                  <Text fontSize="2xs" color="gray.600" mb={2}>
                    Total TOP milestones ({formatIDR(totalTopValues)}) {variance > 0 ? "exceeds" : "is less than"} Total Work Value ({formatIDR(totalWorkValue)}) by {formatIDR(Math.abs(variance))}. Available allocation for remaining unpaid milestones is {formatIDR(remainingBudget)}.
                  </Text>
                  <HStack spacing={2} wrap="wrap">
                    <Button
                      size="xs"
                      colorScheme="teal"
                      variant="solid"
                      onClick={handleSyncWorkValueToTopSum}
                    >
                      Auto-Sync Work Value to TOP Sum ({formatIDR(totalTopValues)})
                    </Button>
                    {unpaidTopList.length > 0 && (
                      <Button
                        size="xs"
                        colorScheme="orange"
                        variant="outline"
                        onClick={handleAutoBalanceRemainingTops}
                      >
                        Auto-Balance Remaining {unpaidTopList.length} Unpaid Step(s)
                      </Button>
                    )}
                  </HStack>
                </Box>
              </Alert>
            ) : (
              <Alert status="success" rounded="xl">
                <AlertIcon />
                <Box flex={1}>
                  <Text fontSize="xs" fontWeight="bold">
                    Reconciliation Perfect: Total TOP Milestones ({formatIDR(totalTopValues)}) matches Total Work Value ({formatIDR(totalWorkValue)})
                  </Text>
                  <Text fontSize="2xs" opacity={0.85}>
                    All payment milestones are allocated with 100% precision matching the total contract value.
                  </Text>
                </Box>
              </Alert>
            )}

            {(formik.values.topList || []).map((top, idx) => {
              const isStepLocked =
                !!top.topStatus &&
                ["SUBMITTED", "VERIFIED", "APPROVED", "PAID"].includes(top.topStatus.toUpperCase());
              const isStepPaid =
                !!top.topStatus && top.topStatus.toUpperCase() === "PAID";

              return (
                <Box
                  key={idx}
                  p={4}
                  rounded="xl"
                  border="1px"
                  borderColor={
                    isStepPaid
                      ? "green.300"
                      : isStepLocked
                      ? "blue.300"
                      : colorMode === "light"
                      ? "gray.200"
                      : "gray.700"
                  }
                  bg={
                    isStepPaid
                      ? colorMode === "light"
                        ? "green.50/30"
                        : "gray.800"
                      : isStepLocked
                      ? colorMode === "light"
                        ? "blue.50/20"
                        : "gray.800"
                      : colorMode === "light"
                      ? "white"
                      : "gray.800"
                  }
                >
                  <VStack align="stretch" spacing={3}>
                    <Flex justify="space-between" align="center">
                      <HStack spacing={2}>
                        <Badge colorScheme="teal" rounded="md" px={2.5} py={0.5} fontSize="2xs">
                          Step #{top.stepOrder}
                        </Badge>
                        {isStepPaid ? (
                          <Badge colorScheme="green" rounded="md" px={2} py={0.5} fontSize="2xs" display="flex" alignItems="center" gap={1}>
                            <Icon as={FiCheck} /> PAID
                          </Badge>
                        ) : top.topStatus && top.topStatus.toUpperCase() === "VERIFIED" ? (
                          <Badge colorScheme="blue" rounded="md" px={2} py={0.5} fontSize="2xs">
                            VERIFIED
                          </Badge>
                        ) : top.topStatus && top.topStatus.toUpperCase() === "SUBMITTED" ? (
                          <Badge colorScheme="yellow" rounded="md" px={2} py={0.5} fontSize="2xs">
                            SUBMITTED
                          </Badge>
                        ) : top.topStatus && top.topStatus.toUpperCase() === "APPROVED" ? (
                          <Badge colorScheme="teal" rounded="md" px={2} py={0.5} fontSize="2xs">
                            APPROVED
                          </Badge>
                        ) : null}

                        {isStepLocked && (
                          <Badge colorScheme="gray" rounded="md" px={2} py={0.5} fontSize="2xs" display="flex" alignItems="center" gap={1}>
                            <Icon as={FiLock} /> Locked
                          </Badge>
                        )}

                        {top.billingPeriodStart && top.billingPeriodEnd && (
                          <Badge colorScheme="purple" rounded="md" px={2} py={0.5} fontSize="2xs">
                            Period: {top.billingPeriodStart} &rarr; {top.billingPeriodEnd}
                          </Badge>
                        )}
                      </HStack>

                      <Button
                        size="xs"
                        colorScheme="red"
                        variant="ghost"
                        isDisabled={isStepLocked}
                        onClick={() => handleRemoveTopStep(idx)}
                        title={isStepLocked ? "Cannot delete step with active or completed payment" : "Remove step"}
                      >
                        <FiTrash2 />
                      </Button>
                    </Flex>

                  <Grid
                    templateColumns={{
                      base: "1fr",
                      md: formik.values.contractBillingType !== "MILESTONE"
                        ? "1.2fr 1.8fr 1fr 1fr"
                        : showTopDates
                        ? "1fr 1fr 1fr"
                        : "1fr 2fr",
                    }}
                    gap={3}
                    alignItems="flex-start"
                  >
                    <GridItem>
                      <FormControl isDisabled={isStepLocked}>
                        <Flex justify="space-between" align="center" mb={1}>
                          <FormLabel fontSize="2xs" fontWeight="bold" m={0}>
                            Payment Amount (Rp.) *
                          </FormLabel>
                          {isStepLocked && (
                            <Badge colorScheme="gray" fontSize="3xs">Locked</Badge>
                          )}
                        </Flex>
                        <CurrencyInput
                          size="sm"
                          rounded="md"
                          name={`topList[${idx}].topValues`}
                          fieldCustom={`topList[${idx}].topValues`}
                          value={top.topValues || 0}
                          isDisabled={isStepLocked}
                          isReadOnly={isStepLocked}
                          onChange={(field, val) => formik.setFieldValue(field, val)}
                        />
                      </FormControl>
                    </GridItem>

                    <GridItem>
                      <FormControl>
                        <FormLabel fontSize="2xs" fontWeight="bold">TOP Description / Milestone Note</FormLabel>
                        <Textarea
                          size="sm"
                          rounded="md"
                          rows={1}
                          placeholder="e.g. DP 30% after signing contract..."
                          value={top.topDescriptions || ""}
                          onChange={(e) => formik.setFieldValue(`topList[${idx}].topDescriptions`, e.target.value)}
                        />
                      </FormControl>
                    </GridItem>

                    {formik.values.contractBillingType !== "MILESTONE" ? (
                      <>
                        <GridItem>
                          <FormControl>
                            <FormLabel fontSize="2xs" fontWeight="bold">Period Start</FormLabel>
                            <Input
                              size="sm"
                              type="date"
                              rounded="md"
                              value={top.billingPeriodStart ? top.billingPeriodStart.split("T")[0] : ""}
                              onChange={(e) => formik.setFieldValue(`topList[${idx}].billingPeriodStart`, e.target.value)}
                            />
                          </FormControl>
                        </GridItem>
                        <GridItem>
                          <FormControl>
                            <FormLabel fontSize="2xs" fontWeight="bold">Period End</FormLabel>
                            <Input
                              size="sm"
                              type="date"
                              rounded="md"
                              value={top.billingPeriodEnd ? top.billingPeriodEnd.split("T")[0] : ""}
                              onChange={(e) => formik.setFieldValue(`topList[${idx}].billingPeriodEnd`, e.target.value)}
                            />
                          </FormControl>
                        </GridItem>
                      </>
                    ) : (
                      showTopDates && (
                        <GridItem>
                          <FormControl>
                            <FormLabel fontSize="2xs" fontWeight="bold">Scheduled Due Date (Optional)</FormLabel>
                            <Input
                              size="sm"
                              type="date"
                              rounded="md"
                              value={top.topDate ? top.topDate.split("T")[0] : ""}
                              onChange={(e) => formik.setFieldValue(`topList[${idx}].topDate`, e.target.value)}
                            />
                          </FormControl>
                        </GridItem>
                      )
                    )}
                  </Grid>
                </VStack>
              </Box>
            );
          })}
        </VStack>
      </CardBody>
      </Card>

      {/* Save Button Bar */}
      <Flex justify="flex-end" pt={2}>
        <Button
          size="md"
          colorScheme="teal"
          leftIcon={<FiSave />}
          px={8}
          rounded="xl"
          shadow="lg"
          isDisabled={
            isDeficitAnomaly || (formik.values.contractBillingType === "MILESTONE" && isScheduleMismatch)
          }
          title={
            isDeficitAnomaly
              ? "Cannot save: Total Work Value is lower than already disbursed amount"
              : formik.values.contractBillingType === "MILESTONE" && isScheduleMismatch
              ? `Cannot save: Milestone TOP schedule (${formatIDR(totalTopValues)}) must match Total Work Value (${formatIDR(totalWorkValue)})`
              : "Save Contract & TOP Changes"
          }
          onClick={handleOpenConfirm}
        >
          Save Contract & TOP Changes
        </Button>
      </Flex>

      {/* 5-second Safety Confirmation Modal */}
      <Modal isOpen={confirmModal.isOpen} onClose={confirmModal.onClose} isCentered>
        <ModalOverlay backdropFilter="blur(4px)" bg="blackAlpha.600" />
        <ModalContent rounded="2xl">
          <ModalHeader borderBottom="1px" borderColor={colorMode === "light" ? "gray.100" : "gray.700"}>
            <HStack spacing={2}>
              <Icon as={FiSave} color="teal.500" />
              <Text fontSize="md" fontWeight="bold">Confirm Contract Edit</Text>
            </HStack>
          </ModalHeader>
          <ModalBody p={5}>
            <VStack align="stretch" spacing={3}>
              <Text fontSize="xs">
                Are you sure you want to save changes to this contract? A historical revision snapshot will automatically be archived in the contract audit logs.
              </Text>

              <Box p={3} rounded="xl" bg={colorMode === "light" ? "gray.50" : "gray.700"} fontSize="xs">
                <VStack align="start" spacing={1.5}>
                  {selectedProject && (
                    <Text><strong>Linked Project:</strong> {selectedProject.projectName} ({selectedProject.projectCode})</Text>
                  )}
                  <Text><strong>SPK / Corp Ref:</strong> {formik.values.corpNumber}</Text>
                  <Text><strong>Project Title:</strong> {formik.values.corpName}</Text>
                  <Text><strong>Contract No:</strong> {formik.values.contractNumber}</Text>
                  <Text><strong>Billing Model:</strong> <Badge colorScheme="purple" fontSize="2xs">{formik.values.contractBillingType || "MILESTONE"}</Badge></Text>
                  <Text><strong>Total Work Value:</strong> <span style={{ color: "#319795", fontWeight: "bold" }}>{formatIDR(formik.values.workValue)}</span></Text>
                  <Text><strong>TOP Steps:</strong> {formik.values.topList?.length || 0} steps ({formatIDR(totalTopValues)})</Text>
                </VStack>
              </Box>
            </VStack>
          </ModalBody>

          <ModalFooter borderTop="1px" borderColor={colorMode === "light" ? "gray.100" : "gray.700"}>
            <HStack spacing={3}>
              <Button size="sm" variant="ghost" onClick={confirmModal.onClose}>
                Cancel
              </Button>
              <Button
                size="sm"
                colorScheme="teal"
                isDisabled={!canSubmit}
                isLoading={isSubmitting}
                onClick={handleExecuteSave}
                leftIcon={<FiCheck />}
              >
                {canSubmit ? "Confirm Save Changes" : `Confirm Save (${countdown}s)`}
              </Button>
            </HStack>
          </ModalFooter>
        </ModalContent>
      </Modal>

      {/* Auto Adjust TOP Generator Modal */}
      <ModalTopAutoAdjust
        isOpen={topAutoAdjustModal.isOpen}
        onClose={topAutoAdjustModal.onClose}
        workValue={formik.values.workValue || 0}
        contractStartDate={formik.values.contractStartDate}
        contractEndDate={formik.values.contractEndDate}
        initialBillingType={formik.values.contractBillingType}
        onApplySchedule={(generated) => formik.setFieldValue("topList", generated)}
      />
    </VStack>
  );
};

export default ContractEditTabPanel;
