// src/app/json/cabRequestMock.ts
// Centralized mock data for CAB Request feature

import { CabActivityItem, CabRequestDetail, CabRequestItem } from "../types/cabTypes";

// ─── Default Activity Checklist for CAB ──────────────────────────────────────
export const DEFAULT_CAB_ACTIVITIES: CabActivityItem[] = [
  {
    id: "act-1",
    label: "Verifikasi Dokumen Permohonan & Kelengkapan RFC/BRD",
    description: "Memastikan form permohonan CAB, rincian teknis, dan dokumen RFC/BRD telah lengkap dan valid.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-2",
    label: "Review Analisis Dampak & Validasi Rencana Rollback",
    description: "Memvalidasi mitigasi risiko downtime, estimasi RTO/RPO, dan ketersediaan script rollback snapshot.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-3",
    label: "Konfirmasi Kesiapan Environment & Ketersediaan Backup",
    description: "Pengecekan kesiapan staging/production, backup snapshot database, dan resource server.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-4",
    label: "Konfirmasi Kehadiran Tim Komite CAB & PIC Migrasi",
    description: "Memastikan seluruh stakeholder, perwakilan tim pengembang, QA, dan PIC operasional siap hadir.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-5",
    label: "Verifikasi Hasil UAT & Sign-off Pengujian",
    description: "Memastikan pengujian fungsional, non-fungsional, dan security assessment telah ditandatangani.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
];

// ─── Mock: Internal BJB Users (non-IT, no real API) ──────────────────────────
export const MOCK_INTERNAL_BJB_USERS = [
  { id: "b-001", name: "Ahmad Fauzi", divisi: "Divisi Operasional" },
  { id: "b-002", name: "Budi Santoso", divisi: "Divisi Keuangan" },
  { id: "b-003", name: "Refan Hidayat", divisi: "Divisi Compliance" },
  { id: "b-004", name: "Dewi Anggraini", divisi: "Divisi Risk Management" },
  { id: "b-005", name: "Hendra Wijaya", divisi: "Divisi Treasury" },
];

export const MOCK_CAB_LIST: CabRequestItem[] = [
  {
    id: "cab-001",
    requestNo: "CAB-2026-001",
    requestTitle: "Deployment Modul Payment Gateway v2.1",
    requestType: "DEPLOYMENT",
    requestDate: "2026-08-10",
    targetDate: "2026-08-20",
    requestedCabDate: "2026-08-19T09:00:00",
    scheduledDate: "2026-08-21T09:00:00",
    scheduledEndDate: "2026-08-21T11:00:00",
    status: "WAITING APPROVE",
    requesterName: "Iqbal Maulana",
    approverName: "Ahmad Fauzi",
    projectName: "Payment Gateway Enhancement",
  },
  {
    id: "cab-002",
    requestNo: "CAB-2026-002",
    requestTitle: "Database Migration - Core Banking Schema Update",
    requestType: "CHANGE REQUEST",
    requestDate: "2026-08-12",
    targetDate: "2026-08-25",
    requestedCabDate: "2026-08-24T10:00:00",
    scheduledDate: "2026-08-26T13:00:00",
    scheduledEndDate: "2026-08-26T15:00:00",
    status: "APPROVED",
    requesterName: "Refan Hidayat",
    approverName: "Ahmad Fauzi",
    projectName: "Core Banking Modernization",
  },
  {
    id: "cab-003",
    requestNo: "CAB-2026-003",
    requestTitle: "Firewall Rule Update - API Gateway",
    requestType: "INFRASTRUCTURE",
    requestDate: "2026-08-14",
    targetDate: "2026-08-18",
    requestedCabDate: "2026-08-17T14:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "REQUEST",
    requesterName: "Deni Saputra",
    approverName: "-",
    projectName: "Network Security Hardening",
  },
  {
    id: "cab-004",
    requestNo: "CAB-2026-004",
    requestTitle: "SSL Certificate Renewal - Production Servers",
    requestType: "MAINTENANCE",
    requestDate: "2026-08-15",
    targetDate: "2026-08-22",
    requestedCabDate: "2026-08-20T10:00:00",
    scheduledDate: "2026-08-22T10:00:00",
    scheduledEndDate: "2026-08-22T11:00:00",
    status: "WAITING APPROVE",
    requesterName: "Rina Marlina",
    approverName: "Budi Santoso",
    projectName: "Infrastructure Maintenance Q3",
  },
  {
    id: "cab-005",
    requestNo: "CAB-2026-005",
    requestTitle: "Hotfix - Login Session Timeout Issue",
    requestType: "HOTFIX",
    requestDate: "2026-08-16",
    targetDate: "2026-08-19",
    requestedCabDate: "2026-08-18T15:00:00",
    scheduledDate: "2026-08-19T08:00:00",
    scheduledEndDate: "2026-08-19T09:00:00",
    status: "WAITING APPROVE",
    requesterName: "Iqbal Maulana",
    approverName: "Ahmad Fauzi",
    projectName: "Mobile Banking App",
  },
  {
    id: "cab-006",
    requestNo: "CAB-2026-006",
    requestTitle: "New Feature - QR Payment Integration",
    requestType: "DEPLOYMENT",
    requestDate: "2026-08-08",
    targetDate: "2026-08-30",
    requestedCabDate: "2026-08-28T09:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "DRAFT",
    requesterName: "Refan Hidayat",
    approverName: "-",
    projectName: "Digital Payment Platform",
  },
  {
    id: "cab-007",
    requestNo: "CAB-2026-007",
    requestTitle: "OS Patching - Ubuntu 24.04 LTS Upgrade",
    requestType: "MAINTENANCE",
    requestDate: "2026-08-17",
    targetDate: "2026-09-01",
    requestedCabDate: "2026-08-30T10:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "REJECTED",
    requesterName: "Deni Saputra",
    approverName: "-",
    projectName: "Server Maintenance Cycle",
  },
  {
    id: "cab-008",
    requestNo: "CAB-2026-008",
    requestTitle: "API Rate Limiter Configuration Update",
    requestType: "INFRASTRUCTURE",
    requestDate: "2026-08-18",
    targetDate: "2026-08-28",
    requestedCabDate: "2026-08-27T14:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "REQUEST",
    requesterName: "Rina Marlina",
    approverName: "-",
    projectName: "API Gateway Optimization",
  },
  {
    id: "cab-009",
    requestNo: "CAB-2026-009",
    requestTitle: "Upgrade Kafka Cluster & Message Queue",
    requestType: "INFRASTRUCTURE",
    requestDate: "2026-08-18",
    targetDate: "2026-08-23",
    requestedCabDate: "2026-08-20T14:00:00",
    scheduledDate: "2026-08-21T13:30:00",
    scheduledEndDate: "2026-08-21T15:00:00",
    status: "WAITING APPROVE",
    requesterName: "Hendra Wijaya",
    approverName: "Budi Santoso",
    projectName: "Event Streaming Platform",
  },
  {
    id: "cab-010",
    requestNo: "CAB-2026-010",
    requestTitle: "Security Patching Microservices Auth Gateway",
    requestType: "HOTFIX",
    requestDate: "2026-08-19",
    targetDate: "2026-08-22",
    requestedCabDate: "2026-08-21T10:00:00",
    scheduledDate: "2026-08-21T15:30:00",
    scheduledEndDate: "2026-08-21T17:00:00",
    status: "WAITING APPROVE",
    requesterName: "Deni Saputra",
    approverName: "Ahmad Fauzi",
    projectName: "Authentication Services",
  },
  {
    id: "cab-011",
    requestNo: "CAB-2026-011",
    requestTitle: "Data Warehouse ETL Pipeline Migration",
    requestType: "CHANGE REQUEST",
    requestDate: "2026-08-15",
    targetDate: "2026-08-24",
    requestedCabDate: "2026-08-21T11:00:00",
    scheduledDate: "2026-08-22T14:00:00",
    scheduledEndDate: "2026-08-22T16:00:00",
    status: "WAITING APPROVE",
    requesterName: "Dewi Anggraini",
    approverName: "Budi Santoso",
    projectName: "Big Data Analytics Modernization",
  },
  {
    id: "cab-012",
    requestNo: "CAB-2026-012",
    requestTitle: "CDN Edge Cache Configuration Update",
    requestType: "INFRASTRUCTURE",
    requestDate: "2026-08-16",
    targetDate: "2026-08-27",
    requestedCabDate: "2026-08-25T13:00:00",
    scheduledDate: "2026-08-26T15:30:00",
    scheduledEndDate: "2026-08-26T17:00:00",
    status: "WAITING APPROVE",
    requesterName: "Refan Hidayat",
    approverName: "Ahmad Fauzi",
    projectName: "Web Portal Optimization",
  },
  {
    id: "cab-013",
    requestNo: "CAB-2026-013",
    requestTitle: "Upgrade Database Replica Server & Read Pool",
    requestType: "INFRASTRUCTURE",
    requestDate: "2026-08-17",
    targetDate: "2026-08-20",
    requestedCabDate: "2026-08-19T09:00:00",
    scheduledDate: "2026-08-19T09:30:00",
    scheduledEndDate: "2026-08-19T11:00:00",
    status: "WAITING APPROVE",
    requesterName: "Hendra Wijaya",
    approverName: "Budi Santoso",
    projectName: "Core DB High Availability",
  },
  {
    id: "cab-014",
    requestNo: "CAB-2026-014",
    requestTitle: "Config Update - Payment Gateway Timeout Limit",
    requestType: "MAINTENANCE",
    requestDate: "2026-08-18",
    targetDate: "2026-08-20",
    requestedCabDate: "2026-08-19T11:00:00",
    scheduledDate: "2026-08-19T11:30:00",
    scheduledEndDate: "2026-08-19T12:30:00",
    status: "WAITING APPROVE",
    requesterName: "Iqbal Maulana",
    approverName: "Ahmad Fauzi",
    projectName: "Payment Gateway Enhancement",
  },
  {
    id: "cab-015",
    requestNo: "CAB-2026-015",
    requestTitle: "Release Modul e-KYC Verification v1.4",
    requestType: "DEPLOYMENT",
    requestDate: "2026-08-16",
    targetDate: "2026-08-21",
    requestedCabDate: "2026-08-19T13:30:00",
    scheduledDate: "2026-08-19T14:00:00",
    scheduledEndDate: "2026-08-19T15:30:00",
    status: "WAITING APPROVE",
    requesterName: "Dewi Anggraini",
    approverName: "Ahmad Fauzi",
    projectName: "Digital Onboarding e-KYC",
  },
  {
    id: "cab-016",
    requestNo: "CAB-2026-016",
    requestTitle: "Patching Nginx Load Balancer Security Header",
    requestType: "HOTFIX",
    requestDate: "2026-08-19",
    targetDate: "2026-08-20",
    requestedCabDate: "2026-08-19T15:30:00",
    scheduledDate: "2026-08-19T16:00:00",
    scheduledEndDate: "2026-08-19T17:30:00",
    status: "WAITING APPROVE",
    requesterName: "Deni Saputra",
    approverName: "Budi Santoso",
    projectName: "Edge Security Hardening",
  },
  {
    id: "cab-017",
    requestNo: "CAB-2026-017",
    requestTitle: "Switchover DR Data Center Mock Drill",
    requestType: "CHANGE REQUEST",
    requestDate: "2026-08-18",
    targetDate: "2026-08-22",
    requestedCabDate: "2026-08-21T17:00:00",
    scheduledDate: "2026-08-21T17:30:00",
    scheduledEndDate: "2026-08-21T18:30:00",
    status: "WAITING APPROVE",
    requesterName: "Rina Marlina",
    approverName: "Budi Santoso",
    projectName: "Business Continuity Plan Q3",
  },
];

export const MOCK_CAB_DETAIL: Record<string, CabRequestDetail> = {
  "cab-001": {
    id: "cab-001",
    requestNo: "CAB-2026-001",
    requestTitle: "Deployment Modul Payment Gateway v2.1",
    requestType: "DEPLOYMENT",
    requestDate: "2026-08-10",
    targetDate: "2026-08-20",
    requestedCabDate: "2026-08-19T09:00:00",
    scheduledDate: "2026-08-21T09:00:00",
    scheduledEndDate: "2026-08-21T11:00:00",
    status: "WAITING APPROVE",
    requesterName: "Iqbal Maulana",
    requesterEmail: "iqbal.maulana@bjb.co.id",
    approverName: "Ahmad Fauzi",
    projectName: "Payment Gateway Enhancement",
    cabLocation: "Ruang Rapat IT Lt. 3",
    description: "Deployment versi terbaru modul payment gateway yang mencakup perbaikan keamanan dan penambahan metode pembayaran baru (QRIS dynamic, Virtual Account multi-bank).",
    impactAnalysis: "Sistem payment gateway akan mengalami downtime sekitar 30 menit selama proses deployment. Nasabah tidak dapat melakukan transaksi pembayaran selama periode tersebut. Estimasi transaksi terdampak: ~500 transaksi.",
    rollbackPlan: "Jika terjadi kegagalan, rollback ke versi v2.0 dapat dilakukan dalam waktu 15 menit menggunakan snapshot pre-deployment. Blue-green deployment strategy digunakan.",
    cabResult: "Deployment berjalan lancar. Semua modul berfungsi normal setelah deployment. Downtime aktual: 25 menit.",
    cabNotes: "Tidak ada insiden selama proses berlangsung. Monitoring 24 jam telah disiapkan.",
    implementationStatus: "SUCCESS",
    approvalHistory: [
      {
        id: "ap-001",
        stepOrder: 1,
        approverName: "Ahmad Fauzi",
        approverRole: "Development Group Head",
        status: "APPROVED",
        actionDate: "2026-08-18T10:30:00",
        note: "Disetujui. Pastikan rollback plan siap dan monitoring 24 jam aktif.",
      },
      {
        id: "ap-002",
        stepOrder: 2,
        approverName: "Budi Santoso",
        approverRole: "IT Operations Division Head",
        status: "PENDING",
        actionDate: null,
        note: null,
      },
    ],
  },
  "cab-003": {
    id: "cab-003",
    requestNo: "CAB-2026-003",
    requestTitle: "Firewall Rule Update - API Gateway",
    requestType: "INFRASTRUCTURE",
    requestDate: "2026-08-14",
    targetDate: "2026-08-18",
    requestedCabDate: "2026-08-17T14:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "REQUEST",
    requesterName: "Deni Saputra",
    requesterEmail: "deni.saputra@bjb.co.id",
    approverName: "-",
    projectName: "Network Security Hardening",
    description: "Update firewall rules pada API Gateway untuk memblokir IP range yang terdeteksi melakukan brute-force attack. Penambahan whitelist untuk partner baru.",
    impactAnalysis: "Perubahan rule bersifat additive. Tidak ada downtime. Risiko: false positive pada legitimate traffic dari IP range baru. Mitigasi: monitoring real-time selama 2 jam pertama.",
    rollbackPlan: "Revert firewall rules ke konfigurasi sebelumnya melalui Terraform state. RTO: 2 menit.",
    approvalHistory: [],
  },
  "cab-004": {
    id: "cab-004",
    requestNo: "CAB-2026-004",
    requestTitle: "SSL Certificate Renewal - Production Servers",
    requestType: "MAINTENANCE",
    requestDate: "2026-08-15",
    targetDate: "2026-08-22",
    requestedCabDate: "2026-08-20T10:00:00",
    scheduledDate: "2026-08-22T10:00:00",
    scheduledEndDate: "2026-08-22T11:00:00",
    status: "WAITING APPROVE",
    requesterName: "Rina Marlina",
    requesterEmail: "rina.marlina@bjb.co.id",
    approverName: "Budi Santoso",
    projectName: "Infrastructure Maintenance Q3",
    cabLocation: "Online - Microsoft Teams",
    description: "Renewal SSL certificate untuk seluruh production servers (12 servers). Certificate lama expired pada 2026-08-30.",
    impactAnalysis: "Proses renewal dilakukan secara rolling. Setiap server akan mengalami restart nginx (~10 detik). Total estimasi: 15 menit dengan zero-downtime approach.",
    rollbackPlan: "Backup certificate lama tersedia. Jika certificate baru gagal, restore certificate lama (masih valid 8 hari).",
    approvalHistory: [],
  },
  "cab-005": {
    id: "cab-005",
    requestNo: "CAB-2026-005",
    requestTitle: "Hotfix - Login Session Timeout Issue",
    requestType: "HOTFIX",
    requestDate: "2026-08-16",
    targetDate: "2026-08-17",
    requestedCabDate: "2026-08-16T15:00:00",
    scheduledDate: "2026-08-17T08:00:00",
    scheduledEndDate: "2026-08-17T09:00:00",
    status: "WAITING APPROVE",
    requesterName: "Iqbal Maulana",
    requesterEmail: "iqbal.maulana@bjb.co.id",
    approverName: "Ahmad Fauzi",
    projectName: "Mobile Banking App",
    cabLocation: "Ruang Rapat IT Lt. 3",
    description: "Hotfix untuk bug session timeout yang menyebabkan user ter-logout setelah 5 menit inactivity. Expected timeout: 30 menit.",
    impactAnalysis: "Hotfix bersifat config change pada session management. Tidak ada downtime. Perubahan efektif segera setelah deployment.",
    rollbackPlan: "Revert config value `SESSION_TIMEOUT_MS` ke nilai sebelumnya (300000ms). Deployment ulang dalam 2 menit.",
    approvalHistory: [
      {
        id: "ap-005-1",
        stepOrder: 1,
        approverName: "Ahmad Fauzi",
        approverRole: "Development Group Head",
        status: "PENDING",
        actionDate: null,
        note: null,
      },
    ],
  },
  "cab-009": {
    id: "cab-009",
    requestNo: "CAB-2026-009",
    requestTitle: "Upgrade Kafka Cluster & Message Queue",
    requestType: "INFRASTRUCTURE",
    requestDate: "2026-08-18",
    targetDate: "2026-08-23",
    requestedCabDate: "2026-08-20T14:00:00",
    scheduledDate: "2026-08-21T13:30:00",
    scheduledEndDate: "2026-08-21T15:00:00",
    status: "WAITING APPROVE",
    requesterName: "Hendra Wijaya",
    requesterEmail: "hendra.wijaya@bjb.co.id",
    approverName: "Budi Santoso",
    projectName: "Event Streaming Platform",
    cabLocation: "Ruang Rapat IT Lt. 2",
    description: "Upgrade version Apache Kafka dari v3.4 ke v3.7 untuk meningkatkan throughput messaging dan stabilitas partition consumer.",
    impactAnalysis: "Rolling restart pada 3 broker Kafka. Estimasi lag time consumer maksimal 2 menit tanpa data loss.",
    rollbackPlan: "Fallback ke snapshot broker image Kafka v3.4 yang telah dicadangkan.",
    approvalHistory: [],
  },
  "cab-010": {
    id: "cab-010",
    requestNo: "CAB-2026-010",
    requestTitle: "Security Patching Microservices Auth Gateway",
    requestType: "HOTFIX",
    requestDate: "2026-08-19",
    targetDate: "2026-08-22",
    requestedCabDate: "2026-08-21T10:00:00",
    scheduledDate: "2026-08-21T15:30:00",
    scheduledEndDate: "2026-08-21T17:00:00",
    status: "WAITING APPROVE",
    requesterName: "Deni Saputra",
    requesterEmail: "deni.saputra@bjb.co.id",
    approverName: "Ahmad Fauzi",
    projectName: "Authentication Services",
    cabLocation: "Online - Microsoft Teams",
    description: "Penambalan kerentanan CVE-2026-XXXX pada library token validation auth gateway.",
    impactAnalysis: "Deployment dilakukan dengan blue-green deployment. Zero downtime.",
    rollbackPlan: "Traffic dialihkan kembali ke cluster blue jika health check gagal.",
    approvalHistory: [],
  },
  "cab-011": {
    id: "cab-011",
    requestNo: "CAB-2026-011",
    requestTitle: "Data Warehouse ETL Pipeline Migration",
    requestType: "CHANGE REQUEST",
    requestDate: "2026-08-15",
    targetDate: "2026-08-24",
    requestedCabDate: "2026-08-21T11:00:00",
    scheduledDate: "2026-08-22T14:00:00",
    scheduledEndDate: "2026-08-22T16:00:00",
    status: "WAITING APPROVE",
    requesterName: "Dewi Anggraini",
    requesterEmail: "dewi.anggraini@bjb.co.id",
    approverName: "Budi Santoso",
    projectName: "Big Data Analytics Modernization",
    cabLocation: "Ruang Rapat IT Lt. 3",
    description: "Migrasi pipeline ETL legacy ke Airflow DAG modern dengan enkripsi data at rest.",
    impactAnalysis: "Job ETL malam hari dipause selama 1 jam saat migrasi skema staging.",
    rollbackPlan: "Re-enable cron job legacy ETL jika job validation test tidak sesuai benchmark.",
    approvalHistory: [],
  },
  "cab-012": {
    id: "cab-012",
    requestNo: "CAB-2026-012",
    requestTitle: "CDN Edge Cache Configuration Update",
    requestType: "INFRASTRUCTURE",
    requestDate: "2026-08-16",
    targetDate: "2026-08-27",
    requestedCabDate: "2026-08-25T13:00:00",
    scheduledDate: "2026-08-26T15:30:00",
    scheduledEndDate: "2026-08-26T17:00:00",
    status: "WAITING APPROVE",
    requesterName: "Refan Hidayat",
    requesterEmail: "refan.hidayat@bjb.co.id",
    approverName: "Ahmad Fauzi",
    projectName: "Web Portal Optimization",
    cabLocation: "Online - Microsoft Teams",
    description: "Pembaruan TTL cache asset statis web portal untuk meningkatkan kecepatan page load.",
    impactAnalysis: "Cache invalidation dilakukan bertahap. Tidak ada dampak gangguan layanan nasabah.",
    rollbackPlan: "Rollback konfigurasi Cloudflare CDN via Terraform provider.",
    approvalHistory: [],
  },
};
