// src/app/json/cabRequestMock.ts
// Centralized mock data for CAB Request feature

import { CabActivityItem, CabRequestDetail, CabRequestItem } from "../types/cabTypes";

// ─── Default Activity Checklist for CAB (Divided by Software / Hardware & Step 3 items) ───
export const DEFAULT_SOFTWARE_CAB_ACTIVITIES: CabActivityItem[] = [
  {
    id: "act-sw-sast",
    label: "SAST (Security Scan)",
    shortLabel: "SAST",
    description: "Verifikasi laporan scanning SAST bebas dari kerentanan critical/high.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-arsitektur",
    label: "Dokumen Arsitektur",
    shortLabel: "Arsitektur",
    description: "Verifikasi diagram sistem, integrasi API, dan standar arsitektur.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-infra",
    label: "Kesiapan Infrastruktur",
    shortLabel: "Infrastruktur",
    description: "Pengecekan kapasitas server, alokasi DB, port, dan environment.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-source",
    label: "Source Aplikasi (Git Tag)",
    shortLabel: "Source Git",
    description: "Verifikasi branch release repository git dan checksum build binary.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-matriks",
    label: "User Matriks & Hak Akses",
    shortLabel: "User Matriks",
    description: "Validasi matriks hak akses pengguna dan segregation of duties.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-rollback",
    label: "Rollback / Fallback Plan",
    shortLabel: "Rollback Plan",
    description: "Validasi snapshot database, backup konfigurasi, dan SOP rollback.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-monitoring",
    label: "Tools / Dashboard Monitoring",
    shortLabel: "Monitoring",
    description: "Memastikan APM, log monitoring, dan alert service aktif.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-security-check",
    label: "Security Checklist",
    shortLabel: "Security Checklist",
    description: "Kepatuhan standar keamanan sistem dan hardening aplikasi.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-approval-sec",
    label: "Persetujuan IT Security",
    shortLabel: "IT Security",
    description: "Sign-off dan clearance dari Divisi IT Security.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-juknis",
    label: "Petunjuk Teknis (Juknis)",
    shortLabel: "Juknis & SOP",
    description: "Manual pengoperasian sistem dan deployment runbook.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-sw-ceklist-migrasi",
    label: "Ceklist & Rundown Migrasi",
    shortLabel: "Rundown Migrasi",
    description: "Rundown jadwal deployment per menit dan PIC pelaksana.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
];

export const DEFAULT_HARDWARE_CAB_ACTIVITIES: CabActivityItem[] = [
  {
    id: "act-hw-checklist",
    label: "Checklist Hardware & DC",
    shortLabel: "Checklist HW",
    description: "Kelengkapan fisik perangkat, part cadangan, dan alokasi rak DC.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-hw-arsitektur",
    label: "Dokumen Arsitektur Hardware",
    shortLabel: "Arsitektur HW",
    description: "Diagram pengkabelan, topologi SAN/LAN/Switch, dan daya listrik.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-hw-test",
    label: "Test Fungsional Hardware",
    shortLabel: "Test Fungsional",
    description: "Diagnostic hardware, burn-in test, dan failover modul redundant.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-hw-rollback",
    label: "Rollback Plan Hardware",
    shortLabel: "Rollback HW",
    description: "SOP fallback ke perangkat cadangan/hot-spare jika terjadi kendala.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-hw-monitoring",
    label: "Perangkat Monitoring Hardware",
    shortLabel: "Monitoring HW",
    description: "Sensor hardware, IPMI/iLO/iDRAC, dan alerting NMS datacenter.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
  {
    id: "act-hw-security",
    label: "Persetujuan IT Security",
    shortLabel: "IT Security HW",
    description: "Hardening port fisik, firmware baseline, dan sign-off IT Security.",
    isDone: false,
    doneAt: null,
    doneBy: null,
  },
];

export const DEFAULT_CAB_ACTIVITIES: CabActivityItem[] = DEFAULT_SOFTWARE_CAB_ACTIVITIES;

/**
 * Generate dynamic CAB activity checklist based on Step 3 inputs (Software vs Hardware).
 * Focuses on verifying items that were not "ADA" / "YA" in the submission,
 * or provides the complete verification list if all were submitted.
 */
export const getDynamicCabActivities = (
  detail: Partial<CabRequestDetail>,
  existingActivities?: CabActivityItem[]
): CabActivityItem[] => {
  const isHardware =
    detail.category === "HARDWARE" ||
    detail.requestType?.toUpperCase().includes("INFRA") ||
    detail.requestType?.toUpperCase().includes("HARDWARE");

  const existingMap = new Map<string, { isDone: boolean; doneAt?: string | null; doneBy?: string | null }>();
  if (existingActivities && existingActivities.length > 0) {
    existingActivities.forEach((act) => {
      existingMap.set(act.id, { isDone: act.isDone, doneAt: act.doneAt, doneBy: act.doneBy });
    });
  }

  const items: CabActivityItem[] = [];

  if (isHardware) {
    const hwFields = [
      {
        id: "act-hw-checklist",
        key: "checklist",
        val: detail.checklist,
        label: "Checklist Hardware & DC",
        shortLabel: "Checklist HW",
        desc: "Kelengkapan fisik perangkat, part cadangan, dan alokasi rak server DC.",
        isPositive: detail.checklist === "ADA",
      },
      {
        id: "act-hw-arsitektur",
        key: "dokumenArsitektur",
        val: detail.dokumenArsitektur,
        label: "Dokumen Arsitektur Hardware",
        shortLabel: "Arsitektur HW",
        desc: "Diagram pengkabelan, topologi SAN/LAN/Switch, dan kapasitas daya listrik.",
        isPositive: detail.dokumenArsitektur === "ADA",
      },
      {
        id: "act-hw-test",
        key: "testFungsional",
        val: detail.testFungsional,
        label: "Test Fungsional Hardware",
        shortLabel: "Test Fungsional",
        desc: "Diagnostic hardware, burn-in test, dan failover redundant komponen.",
        isPositive: detail.testFungsional === "ADA",
      },
      {
        id: "act-hw-rollback",
        key: "rollbackPlan",
        val: detail.rollbackPlan,
        label: "Rollback Plan Hardware",
        shortLabel: "Rollback HW",
        desc: "SOP fallback, perangkat cadangan (hot-spare), dan mitigasi kegagalan.",
        isPositive: Boolean(detail.rollbackPlan && detail.rollbackPlan.trim().length > 0),
      },
      {
        id: "act-hw-monitoring",
        key: "perangkatMonitoring",
        val: detail.perangkatMonitoring,
        label: "Perangkat Monitoring Hardware",
        shortLabel: "Monitoring HW",
        desc: "Integrasi sensor hardware, IPMI/iLO/iDRAC, dan alerting monitoring datacenter.",
        isPositive: detail.perangkatMonitoring === "YA",
      },
      {
        id: "act-hw-security",
        key: "persetujuanItSecurity",
        val: detail.persetujuanItSecurity,
        label: "Persetujuan IT Security",
        shortLabel: "IT Security HW",
        desc: "Hardening port fisik, baseline firmware, dan sign-off Divisi IT Security.",
        isPositive: detail.persetujuanItSecurity === "YA",
      },
    ];

    const nonPositive = hwFields.filter((f) => !f.isPositive);
    const targetFields = nonPositive.length > 0 ? nonPositive : hwFields;

    targetFields.forEach((f) => {
      const existing = existingMap.get(f.id);
      items.push({
        id: f.id,
        label: f.label,
        shortLabel: f.shortLabel,
        description: f.desc,
        isDone: existing ? existing.isDone : false,
        doneAt: existing ? existing.doneAt : null,
        doneBy: existing ? existing.doneBy : null,
        isPendingInitial: !f.isPositive,
      });
    });
  } else {
    const swFields = [
      {
        id: "act-sw-sast",
        key: "sast",
        val: detail.sast,
        label: "SAST (Security Scan)",
        shortLabel: "SAST",
        desc: "Laporan scanning SAST, pastikan temuan critical/high telah diperbaiki.",
        isPositive: detail.sast === "ADA",
      },
      {
        id: "act-sw-arsitektur",
        key: "dokumenArsitektur",
        val: detail.dokumenArsitektur,
        label: "Dokumen Arsitektur",
        shortLabel: "Arsitektur",
        desc: "Diagram alur data, rancangan integrasi API, dan standar arsitektur.",
        isPositive: detail.dokumenArsitektur === "ADA",
      },
      {
        id: "act-sw-infra",
        key: "kesiapanInfrastruktur",
        val: detail.kesiapanInfrastruktur,
        label: "Kesiapan Infrastruktur",
        shortLabel: "Infrastruktur",
        desc: "Alokasi server, resource database, network port, dan environment.",
        isPositive: detail.kesiapanInfrastruktur === "YA",
      },
      {
        id: "act-sw-source",
        key: "sourceAplikasi",
        val: detail.sourceAplikasi,
        label: "Source Aplikasi (Git Tag)",
        shortLabel: "Source Git",
        desc: "Release tag pada repository source code dan checksum integritas build binary.",
        isPositive: detail.sourceAplikasi === "ADA",
      },
      {
        id: "act-sw-matriks",
        key: "userMatriks",
        val: detail.userMatriks,
        label: "User Matriks & Hak Akses",
        shortLabel: "User Matriks",
        desc: "Pemetaan role pengguna, hak akses menu/fitur, dan segregation of duties.",
        isPositive: detail.userMatriks === "ADA",
      },
      {
        id: "act-sw-rollback",
        key: "rollbackPlan",
        val: detail.rollbackPlan,
        label: "Rollback / Fallback Plan",
        shortLabel: "Rollback Plan",
        desc: "SOP rollback, script restore database/snapshot, dan durasi RTO.",
        isPositive: Boolean(detail.rollbackPlan && detail.rollbackPlan.trim().length > 0),
      },
      {
        id: "act-sw-monitoring",
        key: "toolsMonitoring",
        val: detail.toolsMonitoring,
        label: "Tools / Dashboard Monitoring",
        shortLabel: "Monitoring",
        desc: "APM monitoring, health-check endpoint, dan alerting notifikasi insiden.",
        isPositive: detail.toolsMonitoring === "ADA",
      },
      {
        id: "act-sw-security-check",
        key: "securityChecklist",
        val: detail.securityChecklist,
        label: "Security Checklist",
        shortLabel: "Security Checklist",
        desc: "Compliance standar keamanan aplikasi, OWASP top 10 hardening, dan credential.",
        isPositive: detail.securityChecklist === "ADA",
      },
      {
        id: "act-sw-approval-sec",
        key: "persetujuanItSecurity",
        val: detail.persetujuanItSecurity,
        label: "Persetujuan IT Security",
        shortLabel: "IT Security",
        desc: "Sign-off dan clearance persetujuan keamanan dari Tim IT Security.",
        isPositive: detail.persetujuanItSecurity === "YA",
      },
      {
        id: "act-sw-juknis",
        key: "petunjukTeknis",
        val: detail.petunjukTeknis,
        label: "Petunjuk Teknis (Juknis)",
        shortLabel: "Juknis & SOP",
        desc: "Dokumen panduan teknis deployment, petunjuk pengoperasian, dan SOP.",
        isPositive: detail.petunjukTeknis === "ADA",
      },
      {
        id: "act-sw-ceklist-migrasi",
        key: "ceklistMigrasi",
        val: detail.ceklistMigrasi,
        label: "Ceklist & Rundown Migrasi",
        shortLabel: "Rundown Migrasi",
        desc: "Rundown waktu migrasi per jam/menit dan daftar PIC pelaksana deployment.",
        isPositive: detail.ceklistMigrasi === "ADA",
      },
    ];

    const nonPositive = swFields.filter((f) => !f.isPositive);
    const targetFields = nonPositive.length > 0 ? nonPositive : swFields;

    targetFields.forEach((f) => {
      const existing = existingMap.get(f.id);
      items.push({
        id: f.id,
        label: f.label,
        shortLabel: f.shortLabel,
        description: f.desc,
        isDone: existing ? existing.isDone : false,
        doneAt: existing ? existing.doneAt : null,
        doneBy: existing ? existing.doneBy : null,
        isPendingInitial: !f.isPositive,
      });
    });
  }

  return items;
};

// ─── Mock: Internal BJB Users (non-IT, no real API) ──────────────────────────
export const MOCK_INTERNAL_BJB_USERS = [
  { id: "b-001", name: "Ahmad Fauzi", divisi: "Divisi Operasional" },
  { id: "b-002", name: "Budi Santoso", divisi: "Divisi Keuangan" },
  { id: "b-003", name: "Refan Hidayat", divisi: "Divisi Compliance" },
  { id: "b-004", name: "Dewi Anggraini", divisi: "Divisi Risk Management" },
  { id: "b-005", name: "Hendra Wijaya", divisi: "Divisi Treasury" },
];

// ─── MOCK CAB LIST (With 4 standard CAB Types: NEW FEATURE, ENHANCEMENT, BUG FIXING, TOOLS) ───
export const MOCK_CAB_LIST: CabRequestItem[] = [
  // ── PELAKSANAAN (Scheduled by Scheduler, meeting session) ──
  {
    id: "cab-001",
    requestNo: "0001/CAB/08/2026",
    requestTitle: "Deployment Modul Payment Gateway v2.1",
    requestType: "NEW FEATURE",
    category: "SOFTWARE",
    requestDate: "2026-08-10",
    targetDate: "2026-08-21",
    requestedCabDate: "2026-08-19T09:00:00",
    scheduledDate: "2026-08-21T09:00:00",
    scheduledEndDate: "2026-08-21T10:30:00",
    status: "PELAKSANAAN",
    isCabDone: "N",
    cabLocation: "Ruang Rapat IT Lt. 3",
    requesterName: "Iqbal Maulana",
    approverName: "Ahmad Fauzi",
    projectName: "Payment Gateway Enhancement",
    priority: "HIGH",
  },
  // ── COMPLETED (Approved by Approver, final state) ──
  {
    id: "cab-002",
    requestNo: "0002/CAB/08/2026",
    requestTitle: "Database Migration - Core Banking Schema Update",
    requestType: "ENHANCEMENT",
    category: "SOFTWARE",
    requestDate: "2026-08-12",
    targetDate: "2026-08-25",
    requestedCabDate: "2026-08-20T10:00:00",
    scheduledDate: "2026-08-21T11:00:00",
    scheduledEndDate: "2026-08-21T12:30:00",
    status: "COMPLETED",
    isCabDone: "Y",
    cabResult: "APPROVED WITH NOTE",
    cabNotes: "Disetujui dengan catatan: Wajib koordinasi dengan Tim Data Analytics sebelum eksekusi DDL script.",
    cabLocation: "Ruang Rapat IT Lt. 3 & MS Teams",
    requesterName: "Refan Hidayat",
    approverName: "Ahmad Fauzi",
    projectName: "Core Banking Modernization",
    priority: "CRITICAL",
  },
  // ── PENGAJUAN (Submitted by Maker, waiting for Scheduler) ──
  {
    id: "cab-003",
    requestNo: "0003/CAB/08/2026",
    requestTitle: "Firewall Rule Update - API Gateway",
    requestType: "TOOLS",
    category: "HARDWARE",
    requestDate: "2026-08-14",
    targetDate: "2026-08-24",
    requestedCabDate: "2026-08-22T14:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "PENGAJUAN",
    isCabDone: "N",
    requesterName: "Deni Saputra",
    approverName: "Budi Santoso",
    projectName: "Network Security Hardening",
    priority: "MEDIUM",
  },
  // ── PELAKSANAAN ──
  {
    id: "cab-004",
    requestNo: "0004/CAB/08/2026",
    requestTitle: "SSL Certificate Renewal - Production Servers",
    requestType: "TOOLS",
    category: "HARDWARE",
    requestDate: "2026-08-15",
    targetDate: "2026-08-22",
    requestedCabDate: "2026-08-20T10:00:00",
    scheduledDate: "2026-08-22T10:00:00",
    scheduledEndDate: "2026-08-22T11:30:00",
    status: "PELAKSANAAN",
    isCabDone: "N",
    cabLocation: "Online - Microsoft Teams",
    requesterName: "Rina Marlina",
    approverName: "Budi Santoso",
    projectName: "Infrastructure Maintenance Q3",
    priority: "LOW",
  },
  // ── SEND TO APPROVAL (Evaluated, waiting sign-off from Approver) ──
  {
    id: "cab-005",
    requestNo: "0005/CAB/08/2026",
    requestTitle: "Hotfix - Login Session Timeout Issue",
    requestType: "BUG FIXING",
    category: "SOFTWARE",
    requestDate: "2026-08-16",
    targetDate: "2026-08-21",
    requestedCabDate: "2026-08-18T15:00:00",
    scheduledDate: "2026-08-20T13:30:00",
    scheduledEndDate: "2026-08-20T14:30:00",
    status: "SEND TO APPROVAL",
    isCabDone: "Y",
    cabResult: "APPROVED",
    cabNotes: "Patch JWT session expiry fix telah disetujui komite, menunggu sign-off approver.",
    cabLocation: "Ruang Rapat IT Lt. 2",
    requesterName: "Iqbal Maulana",
    approverName: "Ahmad Fauzi",
    projectName: "Mobile Banking App",
    priority: "HIGH",
  },
  // ── COMPLETED ──
  {
    id: "cab-006",
    requestNo: "0006/CAB/08/2026",
    requestTitle: "New Feature - QR Payment Integration",
    requestType: "NEW FEATURE",
    category: "SOFTWARE",
    requestDate: "2026-08-08",
    targetDate: "2026-08-30",
    requestedCabDate: "2026-08-18T09:00:00",
    scheduledDate: "2026-08-19T09:30:00",
    scheduledEndDate: "2026-08-19T11:00:00",
    status: "COMPLETED",
    isCabDone: "Y",
    cabResult: "APPROVED",
    cabNotes: "Modul QRIS merchant payment telah lulus pentest dan UAT.",
    cabLocation: "Ruang Rapat IT Lt. 3",
    requesterName: "Ahmad Fauzi",
    approverName: "Budi Santoso",
    projectName: "Merchant QR Payment Service",
    priority: "MEDIUM",
    buktiImplementasi: [
      {
        id: "bukti-mock-1",
        name: "deployment_verification_qris.png",
        size: 524288,
        url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=60",
        type: "image/png",
        uploadedAt: "2026-08-19T11:15:00Z",
      },
      {
        id: "bukti-mock-2",
        name: "sanity_test_gateway_pass.png",
        size: 734003,
        url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&auto=format&fit=crop&q=60",
        type: "image/png",
        uploadedAt: "2026-08-19T11:20:00Z",
      },
    ],
  },
  // ── COMPLETED ──
  {
    id: "cab-007",
    requestNo: "0007/CAB/08/2026",
    requestTitle: "Upgrade RAM & Storage Server Database DRC",
    requestType: "ENHANCEMENT",
    category: "HARDWARE",
    requestDate: "2026-08-05",
    targetDate: "2026-08-20",
    requestedCabDate: "2026-08-18T13:00:00",
    scheduledDate: "2026-08-19T14:00:00",
    scheduledEndDate: "2026-08-19T15:30:00",
    status: "COMPLETED",
    isCabDone: "Y",
    cabResult: "APPROVED",
    cabNotes: "Penambahan memori node DRC disetujui pada maintenance window.",
    cabLocation: "DC Sudirman Lt. 1",
    requesterName: "Budi Santoso",
    approverName: "Ahmad Fauzi",
    projectName: "DRC Capacity Planning",
    priority: "HIGH",
  },
  // ── COMPLETED ──
  {
    id: "cab-008",
    requestNo: "0008/CAB/08/2026",
    requestTitle: "Enhancement Notifikasi Push WhatsApp OTP",
    requestType: "ENHANCEMENT",
    category: "SOFTWARE",
    requestDate: "2026-08-01",
    targetDate: "2026-08-15",
    requestedCabDate: "2026-08-14T10:00:00",
    scheduledDate: "2026-08-15T10:00:00",
    scheduledEndDate: "2026-08-15T11:30:00",
    status: "COMPLETED",
    isCabDone: "Y",
    cabResult: "APPROVED",
    cabNotes: "Switching vendor SMS OTP ke WhatsApp provider utama disetujui.",
    cabLocation: "Ruang Rapat IT Lt. 3",
    requesterName: "Iqbal Maulana",
    approverName: "Ahmad Fauzi",
    projectName: "Notification Services v3",
    priority: "MEDIUM",
  },
  // ── PELAKSANAAN (Pelaksanaan Rapat CAB terkonfirmasi bersama tim) ──
  {
    id: "cab-009",
    requestNo: "0009/CAB/08/2026",
    requestTitle: "Upgrade Kafka Cluster & Message Queue",
    requestType: "ENHANCEMENT",
    category: "HARDWARE",
    requestDate: "2026-08-18",
    targetDate: "2026-08-24",
    requestedCabDate: "2026-08-20T14:00:00",
    scheduledDate: "2026-08-21T13:30:00",
    scheduledEndDate: "2026-08-21T15:00:00",
    status: "PELAKSANAAN",
    isCabDone: "N",
    cabLocation: "Ruang Rapat IT Lt. 2",
    requesterName: "Hendra Wijaya",
    approverName: "Budi Santoso",
    projectName: "Event Streaming Platform",
    priority: "HIGH",
  },
  // ── COMPLETED (Month 07 resets) ──
  {
    id: "cab-010",
    requestNo: "0001/CAB/07/2026",
    requestTitle: "Security Patching Microservices Auth Gateway",
    requestType: "BUG FIXING",
    category: "SOFTWARE",
    requestDate: "2026-07-10",
    targetDate: "2026-07-16",
    requestedCabDate: "2026-07-14T14:00:00",
    scheduledDate: "2026-07-15T13:30:00",
    scheduledEndDate: "2026-07-15T15:00:00",
    status: "COMPLETED",
    isCabDone: "Y",
    cabResult: "APPROVED",
    cabNotes: "Remediasi celah keamanan CVE-2026-8941 disetujui penuh.",
    cabLocation: "Online - MS Teams",
    requesterName: "Deni Saputra",
    approverName: "Ahmad Fauzi",
    projectName: "Authentication Services",
    priority: "CRITICAL",
  },
  // ── COMPLETED (Month 06 resets) ──
  {
    id: "cab-011",
    requestNo: "0001/CAB/06/2026",
    requestTitle: "Data Warehouse ETL Pipeline Migration",
    requestType: "ENHANCEMENT",
    category: "SOFTWARE",
    requestDate: "2026-06-15",
    targetDate: "2026-06-22",
    requestedCabDate: "2026-06-19T10:00:00",
    scheduledDate: "2026-06-20T10:00:00",
    scheduledEndDate: "2026-06-20T12:00:00",
    status: "COMPLETED",
    isCabDone: "Y",
    cabResult: "APPROVED",
    cabNotes: "Migrasi batch job end-of-month disetujui.",
    cabLocation: "Ruang Rapat IT Lt. 3",
    requesterName: "Dewi Anggraini",
    approverName: "Budi Santoso",
    projectName: "Big Data Analytics Modernization",
    priority: "MEDIUM",
  },
  // ── COMPLETED (Month 03 resets) ──
  {
    id: "cab-012",
    requestNo: "0001/CAB/03/2026",
    requestTitle: "CDN Edge Cache Configuration Update",
    requestType: "TOOLS",
    category: "HARDWARE",
    requestDate: "2026-03-20",
    targetDate: "2026-03-26",
    requestedCabDate: "2026-03-24T14:00:00",
    scheduledDate: "2026-03-25T14:00:00",
    scheduledEndDate: "2026-03-25T15:30:00",
    status: "COMPLETED",
    isCabDone: "Y",
    cabResult: "APPROVED",
    cabNotes: "Optimasi static assets mobile banking disetujui.",
    cabLocation: "Online - MS Teams",
    requesterName: "Deni Saputra",
    approverName: "Ahmad Fauzi",
    projectName: "CDN & Edge Security",
    priority: "LOW",
  },
  // ── REJECTED (Rejected in CAB Meeting / Approval) ──
  {
    id: "cab-013",
    requestNo: "0010/CAB/08/2026",
    requestTitle: "Core Switch Firmware Upgrade Datacenter",
    requestType: "TOOLS",
    category: "HARDWARE",
    requestDate: "2026-08-17",
    targetDate: "2026-08-25",
    requestedCabDate: "2026-08-20T10:00:00",
    scheduledDate: "2026-08-21T16:00:00",
    scheduledEndDate: "2026-08-21T17:00:00",
    status: "REJECTED",
    isCabDone: "Y",
    cabResult: "REJECTED",
    cabNotes: "Ditolak karena belum melampirkan surat jaminan failover dari vendor switch.",
    cabLocation: "DC Sudirman Lt. 2",
    requesterName: "Budi Santoso",
    approverName: "Ahmad Fauzi",
    projectName: "DC Network Core Upgrade",
    priority: "HIGH",
  },
  // ── DRAFT (Draft saved by Maker, not submitted) ──
  {
    id: "cab-014",
    requestNo: "0011/CAB/08/2026",
    requestTitle: "Implementasi Modul e-KYC Facial Recognition v1.0",
    requestType: "NEW FEATURE",
    category: "SOFTWARE",
    requestDate: "2026-08-20",
    targetDate: "2026-08-28",
    requestedCabDate: "2026-08-26T09:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "DRAFT",
    isCabDone: "N",
    requesterName: "Iqbal Maulana",
    approverName: "-",
    projectName: "e-KYC Biometric Verification",
    priority: "HIGH",
  },
  // ── DRAFT ──
  {
    id: "cab-015",
    requestNo: "0012/CAB/08/2026",
    requestTitle: "Penambahan Server Node Worker Redis DRC",
    requestType: "ENHANCEMENT",
    category: "HARDWARE",
    requestDate: "2026-08-21",
    targetDate: "2026-08-29",
    requestedCabDate: "2026-08-27T10:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "DRAFT",
    isCabDone: "N",
    requesterName: "Budi Santoso",
    approverName: "-",
    projectName: "Redis Cluster Capacity Scale-out",
    priority: "MEDIUM",
  },
  // ── PENGAJUAN ──
  {
    id: "cab-016",
    requestNo: "0013/CAB/08/2026",
    requestTitle: "Integrasi Sistem BI-FAST Batch 4",
    requestType: "NEW FEATURE",
    category: "SOFTWARE",
    requestDate: "2026-08-20",
    targetDate: "2026-08-27",
    requestedCabDate: "2026-08-25T09:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "PENGAJUAN",
    isCabDone: "N",
    requesterName: "Refan Hidayat",
    approverName: "Ahmad Fauzi",
    projectName: "BI-FAST Settlement Phase 4",
    priority: "CRITICAL",
  },
  // ── PELAKSANAAN ──
  {
    id: "cab-017",
    requestNo: "0014/CAB/08/2026",
    requestTitle: "Upgrade SAN Storage Array Datacenter Utama",
    requestType: "ENHANCEMENT",
    category: "HARDWARE",
    requestDate: "2026-08-19",
    targetDate: "2026-08-28",
    requestedCabDate: "2026-08-24T14:00:00",
    scheduledDate: "2026-08-25T14:00:00",
    scheduledEndDate: "2026-08-25T15:30:00",
    status: "PELAKSANAAN",
    isCabDone: "N",
    cabLocation: "Ruang Rapat IT Lt. 4",
    requesterName: "Deni Saputra",
    approverName: "Budi Santoso",
    projectName: "SAN Storage Datacenter Upgrade",
    priority: "HIGH",
  },
  // ── IMPLEMENTASI (Evaluasi Migrasi / Mark as Done) ──
  {
    id: "cab-018",
    requestNo: "0015/CAB/08/2026",
    requestTitle: "Pembaruan Microservices Loyalty Points Engine",
    requestType: "ENHANCEMENT",
    category: "SOFTWARE",
    requestDate: "2026-08-18",
    targetDate: "2026-08-24",
    requestedCabDate: "2026-08-20T10:00:00",
    scheduledDate: "2026-08-21T10:00:00",
    scheduledEndDate: "2026-08-21T11:00:00",
    status: "IMPLEMENTASI",
    isCabDone: "Y",
    cabResult: "APPROVED",
    cabNotes: "Pengujian integrasi point engine sukses. Evaluasi migrasi selesai.",
    cabLocation: "Ruang Rapat IT Lt. 3",
    requesterName: "Dewi Anggraini",
    approverName: "Ahmad Fauzi",
    projectName: "Loyalty Points Engine",
    priority: "MEDIUM",
  },
  // ── REJECTED ──
  {
    id: "cab-019",
    requestNo: "0016/CAB/08/2026",
    requestTitle: "Direct Access Port Opening ke Database Production",
    requestType: "BUG FIXING",
    category: "SOFTWARE",
    requestDate: "2026-08-18",
    targetDate: "2026-08-19",
    requestedCabDate: "2026-08-18T09:00:00",
    scheduledDate: "2026-08-18T10:00:00",
    scheduledEndDate: "2026-08-18T10:45:00",
    status: "REJECTED",
    isCabDone: "Y",
    cabResult: "REJECTED",
    cabNotes: "Ditolak oleh Komite CAB karena bypass security checklist tanpa justifikasi darurat yang sah.",
    cabLocation: "Online - MS Teams",
    requesterName: "Iqbal Maulana",
    approverName: "Ahmad Fauzi",
    projectName: "Reporting Ad-hoc Service",
    priority: "CRITICAL",
  },
  // ── CANCELED (Canceled by maker) ──
  {
    id: "cab-020",
    requestNo: "0017/CAB/08/2026",
    requestTitle: "Migrasi Server Legacy Print Statement",
    requestType: "TOOLS",
    category: "HARDWARE",
    requestDate: "2026-08-16",
    targetDate: "2026-08-26",
    requestedCabDate: "2026-08-23T11:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "CANCELED",
    isCabDone: "N",
    cabNotes: "Dibatalkan oleh pengaju karena perubahan arsitektur ke cloud printing.",
    requesterName: "Hendra Wijaya",
    approverName: "-",
    projectName: "Legacy Print Server Migration",
    priority: "LOW",
  },
];

// ─── MOCK CAB DETAIL (Key details) ────────────────────────────────────────────
export const MOCK_CAB_DETAIL: Record<string, CabRequestDetail> = {
  "cab-001": {
    id: "cab-001",
    requestNo: "0001/CAB/08/2026",
    requestTitle: "Deployment Modul Payment Gateway v2.1",
    requestType: "NEW FEATURE",
    tipeCab: "NEW FEATURE",
    category: "SOFTWARE",
    requestDate: "2026-08-10",
    targetDate: "2026-08-21",
    requestedCabDate: "2026-08-19T09:00:00",
    scheduledDate: "2026-08-21T09:00:00",
    scheduledEndDate: "2026-08-21T10:30:00",
    status: "PELAKSANAAN",
    isCabDone: "N",
    requesterName: "Iqbal Maulana",
    requesterEmail: "iqbal.maulana@bjb.co.id",
    approverName: "Ahmad Fauzi",
    projectName: "Payment Gateway Enhancement",
    cabLocation: "Ruang Rapat IT Lt. 3",
    description: "Deployment versi terbaru modul payment gateway yang mencakup perbaikan keamanan dan penambahan metode pembayaran baru (QRIS dynamic, Virtual Account multi-bank).",
    impactAnalysis: "Sistem payment gateway akan mengalami downtime sekitar 30 menit selama proses deployment pada maintenance window non-operasional.",
    rollbackPlan: "Jika terjadi kegagalan, rollback ke versi v2.0 dapat dilakukan dalam waktu 15 menit menggunakan snapshot pre-deployment.",
    approvalHistory: [],
    activityChecklist: DEFAULT_CAB_ACTIVITIES.map((act) => ({ ...act })),
  },
  "cab-002": {
    id: "cab-002",
    requestNo: "0002/CAB/08/2026",
    requestTitle: "Database Migration - Core Banking Schema Update",
    requestType: "ENHANCEMENT",
    tipeCab: "ENHANCEMENT",
    category: "SOFTWARE",
    requestDate: "2026-08-12",
    targetDate: "2026-08-25",
    requestedCabDate: "2026-08-20T10:00:00",
    scheduledDate: "2026-08-21T11:00:00",
    scheduledEndDate: "2026-08-21T12:30:00",
    status: "COMPLETED",
    isCabDone: "Y",
    cabResult: "APPROVED WITH NOTE",
    cabNotes: "Disetujui dengan catatan: Wajib koordinasi dengan Tim Data Analytics sebelum eksekusi DDL script.",
    cabLocation: "Ruang Rapat IT Lt. 3 & MS Teams",
    requesterName: "Refan Hidayat",
    requesterEmail: "refan.hidayat@bjb.co.id",
    approverName: "Ahmad Fauzi",
    projectName: "Core Banking Modernization",
    description: "Penambahan tabel audit dan partisi tabel transaksi history untuk optimasi query batch.",
    impactAnalysis: "Downtime terkendali 45 menit pada maintenance window pukul 01:00-02:00 WIB.",
    rollbackPlan: "Restore snapshot schema database Oracle pre-migration.",
    approvalHistory: [
      {
        id: "ap-002-1",
        stepOrder: 1,
        approverName: "Ahmad Fauzi",
        approverRole: "Development Group Head",
        status: "COMPLETED",
        actionDate: "2026-08-21T12:45:00",
        note: "Disetujui. Pastikan verifikasi data integrity selesai sebelum membuka traffic nasabah.",
      },
    ],
    activityChecklist: DEFAULT_CAB_ACTIVITIES.map((act) => ({ ...act, isDone: true })),
  },
  "cab-003": {
    id: "cab-003",
    requestNo: "0003/CAB/08/2026",
    requestTitle: "Firewall Rule Update - API Gateway",
    requestType: "TOOLS",
    tipeCab: "TOOLS",
    category: "HARDWARE",
    requestDate: "2026-08-14",
    targetDate: "2026-08-24",
    requestedCabDate: "2026-08-22T14:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "PENGAJUAN",
    isCabDone: "N",
    requesterName: "Deni Saputra",
    requesterEmail: "deni.saputra@bjb.co.id",
    approverName: "Budi Santoso",
    projectName: "Network Security Hardening",
    description: "Update firewall rules pada API Gateway untuk memblokir IP range yang terdeteksi brute force attack serta penambahan whitelist partner baru.",
    impactAnalysis: "Perubahan rule bersifat additive. Zero downtime.",
    rollbackPlan: "Revert firewall configuration via Terraform git repo.",
    approvalHistory: [],
    activityChecklist: DEFAULT_CAB_ACTIVITIES.map((act) => ({ ...act })),
  },
  "cab-005": {
    id: "cab-005",
    requestNo: "0005/CAB/08/2026",
    requestTitle: "Hotfix - Login Session Timeout Issue",
    requestType: "BUG FIXING",
    tipeCab: "BUG FIXING",
    category: "SOFTWARE",
    requestDate: "2026-08-16",
    targetDate: "2026-08-21",
    requestedCabDate: "2026-08-18T15:00:00",
    scheduledDate: "2026-08-20T13:30:00",
    scheduledEndDate: "2026-08-20T14:30:00",
    status: "SEND TO APPROVAL",
    isCabDone: "Y",
    cabResult: "APPROVED",
    cabNotes: "Patch JWT session expiry fix telah disetujui komite, menunggu sign-off approver.",
    cabLocation: "Ruang Rapat IT Lt. 2",
    requesterName: "Iqbal Maulana",
    requesterEmail: "iqbal.maulana@bjb.co.id",
    approverName: "Ahmad Fauzi",
    projectName: "Mobile Banking App",
    description: "Hotfix untuk bug session timeout yang menyebabkan user ter-logout prematur setelah 5 menit inactivity.",
    impactAnalysis: "Konfigurasi perubahan token validity. Zero downtime.",
    rollbackPlan: "Revert config value `SESSION_TIMEOUT_MS` ke 1800000ms.",
    approvalHistory: [
      {
        id: "ap-005-1",
        stepOrder: 1,
        approverName: "Ahmad Fauzi",
        approverRole: "Development Group Head",
        status: "PENDING",
        actionDate: null,
        note: null,
      },
    ],
    activityChecklist: DEFAULT_CAB_ACTIVITIES.map((act) => ({ ...act, isDone: true })),
  },
  "cab-013": {
    id: "cab-013",
    requestNo: "0010/CAB/08/2026",
    requestTitle: "Core Switch Firmware Upgrade Datacenter",
    requestType: "TOOLS",
    tipeCab: "TOOLS",
    category: "HARDWARE",
    requestDate: "2026-08-17",
    targetDate: "2026-08-25",
    requestedCabDate: "2026-08-20T10:00:00",
    scheduledDate: "2026-08-21T16:00:00",
    scheduledEndDate: "2026-08-21T17:00:00",
    status: "REJECTED",
    isCabDone: "Y",
    cabResult: "REJECTED",
    cabNotes: "Ditolak karena belum melampirkan surat jaminan failover dari vendor switch.",
    cabLocation: "DC Sudirman Lt. 2",
    requesterName: "Budi Santoso",
    requesterEmail: "budi.santoso@bjb.co.id",
    approverName: "Ahmad Fauzi",
    projectName: "DC Network Core Upgrade",
    description: "Upgrade OS firmware switch Cisco Nexus 9300 series datacenter utama.",
    impactAnalysis: "Terdapat risiko network flapping selama 10 detik.",
    rollbackPlan: "Dual-boot firmware fallback partition.",
    approvalHistory: [
      {
        id: "ap-013-1",
        stepOrder: 1,
        approverName: "Ahmad Fauzi",
        approverRole: "Development Group Head",
        status: "REJECTED",
        actionDate: "2026-08-21T16:45:00",
        note: "Permohonan ditolak. Harap lengkapi sign-off vendor dan lakukan re-submit minggu depan.",
      },
    ],
    activityChecklist: DEFAULT_CAB_ACTIVITIES.map((act) => ({ ...act })),
  },
  "cab-014": {
    id: "cab-014",
    requestNo: "0011/CAB/08/2026",
    requestTitle: "Implementasi Modul e-KYC Facial Recognition v1.0",
    requestType: "NEW FEATURE",
    tipeCab: "NEW FEATURE",
    category: "SOFTWARE",
    requestDate: "2026-08-20",
    targetDate: "2026-08-28",
    requestedCabDate: "2026-08-26T09:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "DRAFT",
    isCabDone: "N",
    requesterName: "Iqbal Maulana",
    requesterEmail: "iqbal.maulana@bjb.co.id",
    approverName: "-",
    projectName: "e-KYC Biometric Verification",
    description: "Integrasi SDK liveness detection dan face match untuk pembukaan rekening online.",
    impactAnalysis: "Layanan baru, tidak berdampak pada transaksi existing.",
    rollbackPlan: "Feature flag toggle `ENABLE_EKYC_V1=false`.",
    approvalHistory: [],
    activityChecklist: DEFAULT_CAB_ACTIVITIES.map((act) => ({ ...act })),
  },
  "cab-020": {
    id: "cab-020",
    requestNo: "0017/CAB/08/2026",
    requestTitle: "Migrasi Server Legacy Print Statement",
    requestType: "TOOLS",
    tipeCab: "TOOLS",
    category: "HARDWARE",
    requestDate: "2026-08-16",
    targetDate: "2026-08-26",
    requestedCabDate: "2026-08-23T11:00:00",
    scheduledDate: null,
    scheduledEndDate: null,
    status: "CANCELED",
    isCabDone: "N",
    cabNotes: "Dibatalkan oleh pengaju karena perubahan arsitektur ke cloud printing.",
    requesterName: "Hendra Wijaya",
    requesterEmail: "hendra.wijaya@bjb.co.id",
    approverName: "-",
    projectName: "Legacy Print Server Migration",
    description: "Migrasi server cetak fisik ke VM terpusat.",
    impactAnalysis: "Tidak ada.",
    rollbackPlan: "Tidak ada.",
    approvalHistory: [],
    activityChecklist: DEFAULT_CAB_ACTIVITIES.map((act) => ({ ...act })),
  },
};

// ─── Mock: Project Files / Attachments ───────────────────────────────────────
export interface ProjectFileItem {
  id: string;
  fileName: string;
  fileSize: string;
  fileType: "pdf" | "docx" | "xlsx" | "zip" | "png" | "drawio";
  category: "Arsitektur" | "Security & SAST" | "UAT & QA" | "BRD & RFC" | "Manual & Runbook";
  uploadedAt: string;
  uploadedBy: string;
  downloadUrl: string;
  projectCode?: string;
  description?: string;
}

export const MOCK_PROJECT_FILES: ProjectFileItem[] = [
  {
    id: "doc-01",
    fileName: "Dokumen_Arsitektur_Sistem_Payment_Gateway_v2.1.pdf",
    fileSize: "4.2 MB",
    fileType: "pdf",
    category: "Arsitektur",
    uploadedAt: "2026-08-15 14:30",
    uploadedBy: "Arsitek Solusi IT",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/architecture/DOC-ARC-2026-089.pdf",
    projectCode: "PRJ-2026-001",
    description: "Spesifikasi arsitektur topologi microservices, network flow, dan disaster recovery gateway.",
  },
  {
    id: "doc-02",
    fileName: "Laporan_SAST_Assessment_Security_Checklist.pdf",
    fileSize: "2.8 MB",
    fileType: "pdf",
    category: "Security & SAST",
    uploadedAt: "2026-08-16 10:15",
    uploadedBy: "Tim IT Security",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/security/SAST-REPORT-2026-AUG.pdf",
    projectCode: "PRJ-2026-001",
    description: "Hasil static application security testing SonarQube & Checkmarx dengan 0 Critical vulnerability.",
  },
  {
    id: "doc-03",
    fileName: "Topologi_Infrastruktur_DRC_HighAvailability.png",
    fileSize: "1.5 MB",
    fileType: "png",
    category: "Arsitektur",
    uploadedAt: "2026-08-14 09:20",
    uploadedBy: "Tim DevOps / Infra",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/architecture/DRC_Topology_Diagram.png",
    projectCode: "PRJ-2026-001",
    description: "Diagram arsitektur jaringan active-passive DC Sudirman - DRC Narogong.",
  },
  {
    id: "doc-04",
    fileName: "SignOff_UAT_Business_Acceptance_Test.pdf",
    fileSize: "1.9 MB",
    fileType: "pdf",
    category: "UAT & QA",
    uploadedAt: "2026-08-17 16:45",
    uploadedBy: "QA Lead",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/uat/UAT-SIGNOFF-PGW-2026.pdf",
    projectCode: "PRJ-2026-001",
    description: "Berita acara dan sign-off hasil UAT pengujian integrasi core banking.",
  },
  {
    id: "doc-05",
    fileName: "BRD_Business_Requirement_Document_RFC-2026-042.docx",
    fileSize: "3.4 MB",
    fileType: "docx",
    category: "BRD & RFC",
    uploadedAt: "2026-08-01 11:00",
    uploadedBy: "Product Owner",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/brd/BRD-RFC-2026-042-v3.docx",
    projectCode: "PRJ-2026-001",
    description: "Dokumen kebutuhan bisnis dan fungsional fitur settlement instan.",
  },
  {
    id: "doc-06",
    fileName: "Runbook_Petunjuk_Teknis_Migrasi_Rollback_v2.pdf",
    fileSize: "2.1 MB",
    fileType: "pdf",
    category: "Manual & Runbook",
    uploadedAt: "2026-08-18 13:10",
    uploadedBy: "Lead Engineer",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/runbook/Runbook_Migration_Rollback.pdf",
    projectCode: "PRJ-2026-001",
    description: "Prosedur langkah demi langkah eksekusi migrasi, fallback step, dan verifikasi post-deployment.",
  },
  {
    id: "doc-07",
    fileName: "Matriks_Akses_Pengguna_UserMatrix_Role.xlsx",
    fileSize: "850 KB",
    fileType: "xlsx",
    category: "Security & SAST",
    uploadedAt: "2026-08-12 15:00",
    uploadedBy: "System Administrator",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/matrix/User_Access_Matrix_2026.xlsx",
    projectCode: "PRJ-2026-001",
    description: "Pemetaan hak akses role operator, supervisor, dan administrator sistem.",
  },
  {
    id: "doc-08",
    fileName: "Security_Hardening_Checklist_Compliant.pdf",
    fileSize: "920 KB",
    fileType: "pdf",
    category: "Security & SAST",
    uploadedAt: "2026-08-15 11:30",
    uploadedBy: "IT Security Compliance",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/security/Security_Hardening_2026.pdf",
    projectCode: "PRJ-2026-001",
    description: "Daftar checklist verifikasi keamanan server, network ports, dan firewall rules.",
  },
  {
    id: "doc-09",
    fileName: "Approval_Memo_Divisi_IT_Security_Signed.pdf",
    fileSize: "510 KB",
    fileType: "pdf",
    category: "Security & SAST",
    uploadedAt: "2026-08-16 16:00",
    uploadedBy: "Divisi IT Security",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/security/IT_Security_Clearance.pdf",
    projectCode: "PRJ-2026-001",
    description: "Surat rekomendasi dan persetujuan deployment dari Kepala Divisi IT Security.",
  },
  {
    id: "doc-10",
    fileName: "Infrastructure_Readiness_Checklist_DRC.pdf",
    fileSize: "840 KB",
    fileType: "pdf",
    category: "Arsitektur",
    uploadedAt: "2026-08-14 16:30",
    uploadedBy: "Tim Infrastruktur & Database",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/infra/Infra_Readiness_Report.pdf",
    projectCode: "PRJ-2026-001",
    description: "Laporan kesiapan resource compute, RAM, storage, dan sinkronisasi DRC.",
  },
  {
    id: "doc-11",
    fileName: "Application_Source_Code_Hash_Verification.pdf",
    fileSize: "420 KB",
    fileType: "pdf",
    category: "Manual & Runbook",
    uploadedAt: "2026-08-17 08:45",
    uploadedBy: "DevOps Engineer",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/build/Release_Tag_SHA256.pdf",
    projectCode: "PRJ-2026-001",
    description: "Verifikasi hash integritas Git tag build commit release.",
  },
  {
    id: "doc-12",
    fileName: "Disaster_Recovery_Rollback_Execution_Plan.docx",
    fileSize: "680 KB",
    fileType: "docx",
    category: "Manual & Runbook",
    uploadedAt: "2026-08-16 14:15",
    uploadedBy: "Lead Engineer",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/plan/DR_Rollback_Plan.docx",
    projectCode: "PRJ-2026-001",
    description: "Rencana snapshot database rollback & blue-green traffic diversion jika migrasi gagal.",
  },
  {
    id: "doc-13",
    fileName: "Monitoring_APM_Grafana_Prometheus_Guide.pdf",
    fileSize: "1.1 MB",
    fileType: "pdf",
    category: "Manual & Runbook",
    uploadedAt: "2026-08-15 13:00",
    uploadedBy: "Site Reliability Engineer",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/monitoring/Monitoring_Setup_Guide.pdf",
    projectCode: "PRJ-2026-001",
    description: "Dashboard URL, alert threshold, dan alerting rule kanal Telegram/Slack.",
  },
  {
    id: "doc-14",
    fileName: "Hardware_Deployment_PreChecklist_DC_v2.pdf",
    fileSize: "1.1 MB",
    fileType: "pdf",
    category: "Manual & Runbook",
    uploadedAt: "2026-08-15 10:00",
    uploadedBy: "Hardware & DC Ops",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/hardware/HW_PreChecklist_DC.pdf",
    projectCode: "PRJ-2026-001",
    description: "Daftar periksa instalasi fisik rack, cabling PDU, dan pendingin ruang server.",
  },
  {
    id: "doc-15",
    fileName: "Topology_Hardware_Network_Storage_v3.1.pdf",
    fileSize: "3.2 MB",
    fileType: "pdf",
    category: "Arsitektur",
    uploadedAt: "2026-08-14 11:20",
    uploadedBy: "Network & Storage Architect",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/hardware/HW_Topology_Storage.pdf",
    projectCode: "PRJ-2026-001",
    description: "Diagram interkoneksi SAN switch, HBA card port, dan VLAN isolasi.",
  },
  {
    id: "doc-16",
    fileName: "Hardware_Diagnostic_Functional_Test_Passed.xlsx",
    fileSize: "890 KB",
    fileType: "xlsx",
    category: "UAT & QA",
    uploadedAt: "2026-08-16 15:40",
    uploadedBy: "QA & HW Tester",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/hardware/Diagnostic_Passed.xlsx",
    projectCode: "PRJ-2026-001",
    description: "Hasil stress test memori, disk I/O benchmark, dan power failover redundancy.",
  },
  {
    id: "doc-17",
    fileName: "Hardware_Fallback_HotSpare_SOP_v1.0.pdf",
    fileSize: "1.3 MB",
    fileType: "pdf",
    category: "Manual & Runbook",
    uploadedAt: "2026-08-15 17:10",
    uploadedBy: "DC Operations Lead",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/hardware/HotSpare_Fallback_SOP.pdf",
    projectCode: "PRJ-2026-001",
    description: "Prosedur aktivasi modul hot-spare cadangan jika terjadi kegagalan modul hardware utama.",
  },
  {
    id: "doc-18",
    fileName: "Zabbix_Grafana_HW_Monitoring_Dashboard_Spec.pdf",
    fileSize: "750 KB",
    fileType: "pdf",
    category: "Manual & Runbook",
    uploadedAt: "2026-08-15 14:00",
    uploadedBy: "NOC & Monitoring Team",
    downloadUrl: "https://kobra.bankbjb.co.id/docs/hardware/HW_Monitoring_Spec.pdf",
    projectCode: "PRJ-2026-001",
    description: "Konfigurasi sensor SNMP, temperatur chassis, dan fan speed threshold alerting.",
  },
];
