"use client";

import { useState } from "react";
import {
  ApiGenericResponse,
  PaggingListPayload,
} from "../types/masterTypes";
import { buildUrlPort } from "../helper/MasterHelper";
import {
  ENDPOINT_API_BASEURL,
  ENDPOINT_PORT_BASIC,
  RES_CODE_SERVER_ERROR,
} from "../constants/applicationConstants";
import axiosInstance from "../utils/axiosInstance";
import axios from "axios";
import handleAxiosError from "../utils/handleAxiosError";
import { RequirementWorkProgramDataResponse } from "./useRequirements";

// ─── Request Interfaces ──────────────────────────────────────────────────────

export interface VendorTdrInsertPayload {
  trdNumber: string;
  tdrType: string;
  npwpNumber: string;
  yearRegistered: string;
  businessType: string;
  businessSectorCode: string;
  businessSectorName: string;
  subBusinessSector?: string | null;
  qualifications?: string | null;
  timeInEffect: string;
  expiredAt: string;
}

export interface VendorInsertPayload {
  vendorCode: string;
  vendorName: string;
  vendorType: string;
  address1: string;
  address2?: string | null;
  address3?: string | null;
  city: string;
  country: string;
  postalCode?: string | null;
  website?: string | null;
  picBusinessName: string;
  picBusinessEmail: string;
  picBusinessNumberHotline?: string | null;
  picTechnicalName: string;
  picTechnicalEmail: string;
  picTechnicalNumberHotline?: string | null;
  status: string;
  reasonStatus?: string | null;
  depedencyLevel: string;
  businessImpact: string;
  tdr: VendorTdrInsertPayload[];
}

export interface VendorUpdatePayload {
  id: string;
  vendorCode: string;
  vendorName: string;
  vendorType: string;
  address1: string;
  address2?: string | null;
  address3?: string | null;
  city: string;
  country: string;
  postalCode?: string | null;
  website?: string | null;
  picBusinessName: string;
  picBusinessEmail: string;
  picBusinessNumberHotline?: string | null;
  picTechnicalName: string;
  picTechnicalEmail: string;
  picTechnicalNumberHotline?: string | null;
  status: string;
  reasonStatus?: string | null;
  depedencyLevel: string;
  businessImpact: string;
}

// ─── Response Interfaces ────────────────────────────────────────────────────

export interface VendorMediaResponse {
  relId: string;
  mediaId: string;
  objectCode: string;
  objectName: string;
  objectRawName: string;
  objectData: string;
  objectExtension?: string | null;
  objectSize?: number | null;
  createdAt: string;
}

export interface ContractItemResponse {
  id: string;
  venContractId: string;
  itemCode?: string | null;
  itemName: string;
  itemDesc?: string | null;
  itemType: string;
  brand?: string | null;
  itemValues: number;
  createdAt: string;
  createdBy: string;
  updatedAt?: string | null;
  updatedBy?: string | null;
}

export interface ContractTopResponse {
  id: string;
  venContractId: string;
  stepOrder: number;
  topValues: number;
  topDate?: string | null;
  topDescriptions?: string | null;
  topStatus?: string | null;
  billingPeriodStart?: string | null;
  billingPeriodEnd?: string | null;
  isAutoGenerated?: boolean | null;
  createdAt: string;
  createdBy: string;
  updatedAt?: string | null;
  updatedBy?: string | null;
  mediaList: VendorMediaResponse[];
  topAttachments?: ContractPaymentTopAttachmentResponse[];
}

export interface ContractPaymentTopAttachmentResponse {
  id: string;
  contractPaymentId: string;
  contractTopId: string;
  mediaObjectId?: string | null;
  documentType: string;
  documentName: string;
  documentNumber: string;
  documentDate: string;
  documentVersion?: string | null;
  linkAttachment?: string | null;
  topRealizationAmount?: number | null;
  taxInvoiceNumber?: string | null;
  paymentStatus: string;
  note?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
  updatedAt?: string | null;
  updatedBy?: string | null;
  mediaObject?: VendorMediaResponse | null;
}

export interface ContractTopStatusUpdatePayload {
  contractTopId: string;
  topStatus: string;
  topDescriptions?: string | null;
  topDate?: string | null;
  note?: string | null;
}

export interface ContractHpsItemPayload {
  id?: string | null;
  costGovernanceId?: string | null;
  venContractId?: string | null;
  hpsKey: string;
  hpsName: string;
  hpsTag: string;
  hpsNominal: number;
  isBenchmark?: boolean;
  isRemovable?: boolean;
  stepOrder: number;
  diffRbbNominal: number;
  diffRbbPercentage: number;
  diffRbbStatus: string;
  diffContractNominal: number;
  diffContractPercentage: number;
  diffContractStatus: string;
  notes?: string | null;
}

export interface ContractCostGovernanceSavePayload {
  id?: string | null;
  venContractId: string;
  projectId?: string | null;
  totalBudgetRbb: number;
  contractWorkValue: number;
  benchmarkHpsId?: string | null;
  benchmarkHpsKey?: string | null;
  globalResapanNominal: number;
  globalResapanPercentage: number;
  globalResapanStatus: string;
  hpsSpreadNominal?: number | null;
  itVsKomiteDelta?: number | null;
  itVsKomitePercentage?: number | null;
  governanceNotes?: string | null;
  status?: string;
  revisionReason?: string | null;
  hpsItems: ContractHpsItemPayload[];
}

export interface ContractHpsItemResponse {
  id: string;
  costGovernanceId: string;
  venContractId: string;
  hpsKey: string;
  hpsName: string;
  hpsTag: string;
  hpsNominal: number;
  isBenchmark: boolean;
  isRemovable: boolean;
  stepOrder: number;
  diffRbbNominal: number;
  diffRbbPercentage: number;
  diffRbbStatus: string;
  diffContractNominal: number;
  diffContractPercentage: number;
  diffContractStatus: string;
  notes?: string | null;
  createdAt: string;
  createdBy: string;
  updatedAt?: string | null;
  updatedBy?: string | null;
}

export interface ContractCostGovernanceResponse {
  id: string;
  venContractId: string;
  projectId?: string | null;
  totalBudgetRbb: number;
  contractWorkValue: number;
  benchmarkHpsId?: string | null;
  benchmarkHpsKey?: string | null;
  globalResapanNominal: number;
  globalResapanPercentage: number;
  globalResapanStatus: string;
  hpsSpreadNominal?: number | null;
  itVsKomiteDelta?: number | null;
  itVsKomitePercentage?: number | null;
  governanceNotes?: string | null;
  status: string;
  createdAt: string;
  createdBy: string;
  updatedAt?: string | null;
  updatedBy?: string | null;
  hpsItems: ContractHpsItemResponse[];
}

export interface ContractHpsItemHistoryResponse {
  id: string;
  costGovHistoryId: string;
  hpsItemParentId?: string | null;
  hpsKey: string;
  hpsName: string;
  hpsTag: string;
  hpsNominal: number;
  isBenchmark?: boolean | null;
  diffRbbNominal: number;
  diffRbbPercentage: number;
  diffRbbStatus: string;
  diffContractNominal: number;
  diffContractPercentage: number;
  diffContractStatus: string;
  createdAt: string;
  createdBy: string;
}

export interface ContractCostGovHistoryResponse {
  id: string;
  costGovernanceParentId: string;
  venContractId: string;
  venContractHistoryId?: string | null;
  projectId?: string | null;
  totalBudgetRbb: number;
  contractWorkValue: number;
  benchmarkHpsKey?: string | null;
  globalResapanNominal: number;
  globalResapanPercentage: number;
  globalResapanStatus: string;
  hpsSpreadNominal?: number | null;
  itVsKomiteDelta?: number | null;
  itVsKomitePercentage?: number | null;
  revisionReason?: string | null;
  createdAt: string;
  createdBy: string;
  hpsItemsHistory: ContractHpsItemHistoryResponse[];
}

export interface VendorContractResponse {
  id: string;
  vendorId: string;
  corpNumber: string;
  corpName: string;
  contractNumber: string;
  contractDate: string;
  workValue: number;
  note?: string | null;
  contractStartDate: string;
  contractEndDate: string;
  worksStartDate?: string | null;
  worksEndDate?: string | null;
  warrantyStartDate?: string | null;
  warrantyEndDate?: string | null;
  maintenanceStartDate?: string | null;
  maintenanceEndDate?: string | null;
  othersTimeline?: string | null;
  termOfPayment?: string | null;
  performanceGuaranteeStartDate: string;
  performanceGuaranteeEndDate: string;
  performanceGuaranteeValues: number;
  maintenanceWarrantyStartDate: string;
  maintenanceWarrantyEndDate: string;
  maintenanceWarrantyValues: number;
  cavexValues: number;
  capexPercentage: number;
  ovexValues: number;
  ovexPercentage: number;
  status: string;
  contractBillingType?: string | null;
  subscriptionPeriodValue?: number | null;
  subscriptionAutoRenew?: boolean | null;
  vendorCode?: string | null;
  vendorName?: string | null;
  projectId?: string | null;
  projectNo?: string | null;
  projectCode?: string | null;
  projectName?: string | null;
  proOwnerDivisionName?: string | null;
  proOwnerDirectorateName?: string | null;
  sdlcStageName?: string | null;
  createdAt: string;
  createdBy: string;
  updatedAt?: string | null;
  updatedBy?: string | null;
  items: ContractItemResponse[];
  topList: ContractTopResponse[];
  mediaList: VendorMediaResponse[];
  historyList?: VendorContractHistoryResponse[];
  vendor?: VendorResponse | null;
  costGovernance?: ContractCostGovernanceResponse | null;
  workPrograms?: RequirementWorkProgramDataResponse[] | null;
}

export interface ContractTopHistoryResponse {
  id: string;
  venContractParentId?: string | null;
  venContractId?: string | null;
  venContractHistoryId?: string | null;
  stepOrder?: number | null;
  topValues?: number | null;
  topDate?: string | null;
  topDescriptions?: string | null;
  topStatus?: string | null;
  billingPeriodStart?: string | null;
  billingPeriodEnd?: string | null;
  isAutoGenerated?: boolean | null;
  createdAt?: string | null;
  createdBy?: string | null;
  updatedAt?: string | null;
  updatedBy?: string | null;
}

export interface VendorContractHistoryResponse {
  id: string;
  venContractParentId: string;
  vendorId: string;
  projectId?: string | null;
  projectNo?: string | null;
  projectCode?: string | null;
  projectName?: string | null;
  proOwnerDivisionName?: string | null;
  proOwnerDirectorateName?: string | null;
  sdlcStageName?: string | null;
  corpNumber: string;
  corpName: string;
  contractNumber: string;
  contractDate: string;
  workValue: number;
  note?: string | null;
  contractStartDate: string;
  contractEndDate: string;
  worksStartDate?: string | null;
  worksEndDate?: string | null;
  warrantyStartDate?: string | null;
  warrantyEndDate?: string | null;
  maintenanceStartDate?: string | null;
  maintenanceEndDate?: string | null;
  othersTimeline?: string | null;
  termOfPayment?: string | null;
  performanceGuaranteeStartDate: string;
  performanceGuaranteeEndDate: string;
  performanceGuaranteeValues: number;
  maintenanceWarrantyStartDate: string;
  maintenanceWarrantyEndDate: string;
  maintenanceWarrantyValues: number;
  cavexValues: number;
  capexPercentage: number;
  ovexValues: number;
  ovexPercentage: number;
  status: string;
  contractBillingType?: string | null;
  subscriptionPeriodValue?: number | null;
  subscriptionAutoRenew?: boolean | null;
  createdAt: string;
  createdBy: string;
  updatedAt?: string | null;
  updatedBy?: string | null;
  topHistoryList?: ContractTopHistoryResponse[];
  costGovernanceHistory?: ContractCostGovHistoryResponse | null;
}

export interface VendorTdrResponse {
  id: string;
  vendorId: string;
  trdNumber: string;
  tdrType: string;
  npwpNumber: string;
  yearRegistered: string;
  businessType: string;
  businessSectorCode: string;
  businessSectorName: string;
  subBusinessSector?: string | null;
  qualifications?: string | null;
  timeInEffect: string;
  expiredAt: string;
  createdAt: string;
  createdBy: string;
  updatedAt?: string | null;
  updatedBy?: string | null;
  mediaList: VendorMediaResponse[];
}

export interface VendorResponse {
  id: string;
  vendorCode: string;
  vendorName: string;
  vendorType: string;
  address1: string;
  address2?: string | null;
  address3?: string | null;
  city: string;
  country: string;
  postalCode?: string | null;
  vendorLogo?: string | null;
  website?: string | null;
  picBusinessName: string;
  picBusinessEmail: string;
  picBusinessNumberHotline?: string | null;
  picTechnicalName: string;
  picTechnicalEmail: string;
  picTechnicalNumberHotline?: string | null;
  status: string;
  reasonStatus?: string | null;
  depedencyLevel: string;
  businessImpact: string;
  createdAt: string;
  createdBy: string;
  updatedAt?: string | null;
  updatedBy?: string | null;
  tdrList: VendorTdrResponse[];
  contractList: VendorContractResponse[];
}

export interface ContractItemInsertPayload {
  itemCode?: string;
  itemName: string;
  itemDesc?: string;
  itemType: string;
  brand?: string;
  itemValues: number;
}

export interface ContractTopInsertPayload {
  id?: string;
  stepOrder: number;
  topValues: number;
  topDate?: string;
  topDescriptions?: string;
  topStatus?: string;
  billingPeriodStart?: string;
  billingPeriodEnd?: string;
  isAutoGenerated?: boolean;
}

export interface VendorContractInsertPayload {
  id?: string;
  projectId?: string | null;
  vendorId: string;
  corpNumber: string;
  corpName: string;
  contractNumber: string;
  contractDate: string;
  workValue: number;
  note?: string;
  contractStartDate: string;
  contractEndDate: string;
  worksStartDate?: string;
  worksEndDate?: string;
  warrantyStartDate?: string;
  warrantyEndDate?: string;
  maintenanceStartDate?: string;
  maintenanceEndDate?: string;
  othersTimeline?: string;
  termOfPayment?: string;
  performanceGuaranteeStartDate?: string;
  performanceGuaranteeEndDate?: string;
  performanceGuaranteeValues?: number;
  maintenanceWarrantyStartDate?: string;
  maintenanceWarrantyEndDate?: string;
  maintenanceWarrantyValues?: number;
  cavexValues?: number;
  capexPercentage?: number;
  ovexValues?: number;
  ovexPercentage?: number;
  status?: string;
  contractBillingType?: string;
  subscriptionPeriodValue?: number;
  subscriptionAutoRenew?: boolean;
  items?: ContractItemInsertPayload[];
  topList?: ContractTopInsertPayload[];
}

export interface ContractPaymentWorkProgramPayload {
  id?: string;
  reqWorkProgramId?: string | null;
  reqId?: string | null;
  workProgramSource?: string;
  workProgramCode?: string | null;
  workProgramName?: string | null;
  workProgramAccName?: string | null;
  workProgramAccNumber?: string | null;
  workProgramAccCc?: string | null;
  workProgramBudget?: number;
  workProgramReal?: number;
  workProgramLeftovers?: number;
  divisionId: string;
  divisionCode: string;
  divisionName: string;
  directorateId?: string | null;
  directorateCode?: string | null;
  directorateName?: string | null;
  groupId?: string | null;
  groupCode?: string | null;
  groupName?: string | null;
}

export interface ContractPaymentWorkProgramResponse {
  id: string;
  contractPayment: string;
  reqWorkProgramId?: string | null;
  reqId?: string | null;
  workProgramSource: string;
  workProgramCode?: string | null;
  workProgramName?: string | null;
  workProgramAccName?: string | null;
  workProgramAccNumber?: string | null;
  workProgramAccCc?: string | null;
  workProgramBudget: number;
  workProgramReal: number;
  workProgramLeftovers: number;
  divisionId: string;
  divisionCode: string;
  divisionName: string;
  directorateId?: string | null;
  directorateCode?: string | null;
  directorateName?: string | null;
  groupId?: string | null;
  groupCode?: string | null;
  groupName?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
  updatedAt?: string | null;
  updatedBy?: string | null;
}

export interface ContractPaymentInsertPayload {
  projectId: string;
  venContractId: string;
  vendorId: string;
  paymentNo?: string;
  paymentMemoNo?: string;
  paymentContractWorkValue: number;
  paymentContractChangeValue: number;
  paymentContractStepChangeNumber: number;
  paymentStatus?: string;
  paymentStatusDate?: string | null;
  workPrograms?: ContractPaymentWorkProgramPayload[];
}

export interface ContractPaymentUpdatePayload {
  id: string;
  paymentNo?: string;
  paymentMemoNo?: string;
  paymentContractWorkValue: number;
  paymentContractChangeValue: number;
  paymentContractStepChangeNumber: number;
  paymentStatus?: string;
  paymentStatusDate?: string | null;
  workPrograms?: ContractPaymentWorkProgramPayload[];
}

export interface ContractPaymentResponse {
  id: string;
  projectId: string;
  projectNo: string;
  projectCode: string;
  projectName: string;
  projectCategory: string;
  projectType: string;
  projectRegisterDate?: string | null;
  projectClosedDate?: string | null;
  proOwnerDivisionId?: string | null;
  proOwnerDivisionCode?: string | null;
  proOwnerDivisionName?: string | null;
  proOwnerGroupId?: string | null;
  proOwnerGroupCode?: string | null;
  proOwnerGroupName?: string | null;
  proManageByDivisionId?: string | null;
  proManageByDivisionCode?: string | null;
  proManageByDivisionName?: string | null;
  proManageByGroupId?: string | null;
  proManageByGroupCode?: string | null;
  proManageByGroupName?: string | null;
  proManageByTeamId?: string | null;
  proManageByTeamCode?: string | null;
  proManageByTeamName?: string | null;
  proOwnerDirectorateId?: string | null;
  proOwnerDirectorateCode?: string | null;
  proOwnerDirectorateName?: string | null;
  proManageByDirectorateId?: string | null;
  proManageByDirectorateCode?: string | null;
  proManageByDirectorateName?: string | null;
  projectAcquisitionCode?: string | null;
  projectAcquisitionName?: string | null;
  projectCharasteristicCode?: string | null;
  projectCharasteristicName?: string | null;
  projectSubCharasteristicCode?: string | null;
  projectSubCharasteristicName?: string | null;
  projectSubCharasteristicDesc?: string | null;
  venContractId: string;
  vendorId: string;
  vendorCode: string;
  vendorName: string;
  vendorType: string;
  vendorAddress1: string;
  vendorAddress2?: string | null;
  vendorAddress3?: string | null;
  vendorCity: string;
  vendorCountry: string;
  vendorPostalCode?: string | null;
  vendorVendorLogo?: string | null;
  vendorWebsite?: string | null;
  vendorPicBusinessNumberHotline?: string | null;
  vendorPicBusinessName: string;
  vendorPicBusinessEmail: string;
  vendorPicTechnicalNumberHotline?: string | null;
  vendorPicTechnicalName: string;
  vendorPicTechnicalEmail: string;
  paymentNo?: string | null;
  paymentMemoNo?: string | null;
  paymentContractWorkValue: number;
  paymentContractChangeValue: number;
  paymentContractStepChangeNumber: number;
  paymentStatus: string;
  paymentStatusDate?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
  updatedAt?: string | null;
  updatedBy?: string | null;
  workPrograms: ContractPaymentWorkProgramResponse[];
  attachments?: ContractPaymentAttachmentResponse[];
  topAttachments?: ContractPaymentTopAttachmentResponse[];
}

export interface ContractPaymentAttachmentResponse {
  id: string;
  contractPayment: string;
  documentType: string;
  documentName: string;
  documentNumber: string;
  documentDate: string;
  documentVersion: string;
  linkAttachment?: string | null;
  mediaObjectId?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
  updatedAt?: string | null;
  updatedBy?: string | null;
  mediaObject?: VendorMediaResponse | null;
}

// ─── Service Interface ───────────────────────────────────────────────────────

interface useVendorServices {
  List: (
    payload: PaggingListPayload,
    token: string
  ) => Promise<ApiGenericResponse<VendorResponse[] | null> | null>;
  GetDetailById: (
    id: string,
    token: string
  ) => Promise<ApiGenericResponse<VendorResponse | null> | null>;
  Register: (
    payload: VendorInsertPayload,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  Update: (
    payload: VendorUpdatePayload,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  ListTdr: (
    payload: PaggingListPayload,
    token: string
  ) => Promise<ApiGenericResponse<VendorTdrResponse[] | null> | null>;
  ListContract: (
    payload: PaggingListPayload,
    token: string
  ) => Promise<ApiGenericResponse<VendorContractResponse[] | null> | null>;
  InsertContract: (
    payload: VendorContractInsertPayload,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  GetContractDetail: (
    id: string,
    token: string
  ) => Promise<ApiGenericResponse<VendorContractResponse | null> | null>;
  ListPayment: (
    payload: PaggingListPayload,
    token: string
  ) => Promise<ApiGenericResponse<ContractPaymentResponse[] | null> | null>;
  GetPaymentDetail: (
    id: string,
    token: string
  ) => Promise<ApiGenericResponse<ContractPaymentResponse | null> | null>;
  GetPaymentByContractId: (
    contractId: string,
    token: string
  ) => Promise<ApiGenericResponse<ContractPaymentResponse | null> | null>;
  InsertPayment: (
    payload: ContractPaymentInsertPayload,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  UpdatePayment: (
    payload: ContractPaymentUpdatePayload,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  DeletePayment: (
    id: string,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  UploadPaymentAttachment: (
    formData: FormData,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  DeletePaymentAttachment: (
    id: string,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  GetTopAttachmentsByTopId: (
    topId: string,
    token: string
  ) => Promise<ApiGenericResponse<ContractPaymentTopAttachmentResponse[] | null> | null>;
  UploadTopAttachment: (
    formData: FormData,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  DeleteTopAttachment: (
    id: string,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  UpdateContractTopStatus: (
    payload: ContractTopStatusUpdatePayload,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  RecalculateMasterPayment: (
    contractPaymentId: string,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  GetCostGovernanceByContractId: (
    contractId: string,
    token: string
  ) => Promise<ApiGenericResponse<ContractCostGovernanceResponse | null> | null>;
  SaveCostGovernance: (
    payload: ContractCostGovernanceSavePayload,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  GetCostGovHistoryList: (
    contractId: string,
    token: string
  ) => Promise<ApiGenericResponse<ContractCostGovHistoryResponse[] | null> | null>;
  InsertTdr: (
    formData: FormData,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  UpdateTdr: (
    formData: FormData,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  DeleteTdrMedia: (
    relId: string,
    token: string
  ) => Promise<ApiGenericResponse<string | null> | null>;
  isLoading: boolean;
  error: string | null;
}

// ─── Hook ────────────────────────────────────────────────────────────────────

const useVendor = (): useVendorServices => {
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const List = async (
    payload: PaggingListPayload,
    token: string
  ): Promise<ApiGenericResponse<VendorResponse[] | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(
      ENDPOINT_API_BASEURL,
      ENDPOINT_PORT_BASIC
    );
    const PathEndpoint: string = "/v1/Vendor/list";
    try {
      const response = await axiosInstance.post<
        ApiGenericResponse<VendorResponse[]>
      >(`${UrlEndpoint}${PathEndpoint}`, payload, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        const errorResponse = handleAxiosError(err);
        setError(err.response?.data?.message || "An error occurred during request.");
        return errorResponse;
      } else {
        setError("An unknown error occurred. Please try again.");
        return {
          statusCode: RES_CODE_SERVER_ERROR,
          data: null,
          message: "Error connect to api",
          error: null,
        };
      }
    }
  };

  const GetDetailById = async (
    id: string,
    token: string
  ): Promise<ApiGenericResponse<VendorResponse | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(
      ENDPOINT_API_BASEURL,
      ENDPOINT_PORT_BASIC
    );
    const PathEndpoint: string = `/v1/Vendor/${id}`;
    try {
      const response = await axiosInstance.get<
        ApiGenericResponse<VendorResponse>
      >(`${UrlEndpoint}${PathEndpoint}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        const errorResponse = handleAxiosError(err);
        setError(err.response?.data?.message || "An error occurred during request.");
        return errorResponse;
      } else {
        setError("An unknown error occurred. Please try again.");
        return {
          statusCode: RES_CODE_SERVER_ERROR,
          data: null,
          message: "Error connect to api",
          error: null,
        };
      }
    }
  };

  const Register = async (
    payload: VendorInsertPayload,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    const PathEndpoint: string = "/v1/Vendor/register";
    try {
      const response = await axiosInstance.post<ApiGenericResponse<string>>(
        `${UrlEndpoint}${PathEndpoint}`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        const errorResponse = handleAxiosError(err);
        setError(err.response?.data?.message || "An error occurred during request.");
        return errorResponse;
      } else {
        setError("An unknown error occurred. Please try again.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error connect to api", error: null };
      }
    }
  };

  const Update = async (
    payload: VendorUpdatePayload,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    const PathEndpoint: string = "/v1/Vendor/update";
    try {
      const response = await axiosInstance.put<ApiGenericResponse<string>>(
        `${UrlEndpoint}${PathEndpoint}`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        const errorResponse = handleAxiosError(err);
        setError(err.response?.data?.message || "An error occurred during request.");
        return errorResponse;
      } else {
        setError("An unknown error occurred. Please try again.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error connect to api", error: null };
      }
    }
  };

  const ListTdr = async (
    payload: PaggingListPayload,
    token: string
  ): Promise<ApiGenericResponse<VendorTdrResponse[] | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<VendorTdrResponse[]>>(
        `${UrlEndpoint}/v1/Vendor/tdr/list`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const InsertTdr = async (
    formData: FormData,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/tdr/insert`,
        formData,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "multipart/form-data",
          },
        }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error connect to api", error: null };
    }
  };

  const UpdateTdr = async (
    formData: FormData,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.put<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/tdr/update`,
        formData,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "multipart/form-data",
          },
        }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error connect to api", error: null };
    }
  };

  const DeleteTdrMedia = async (
    relId: string,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.delete<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/tdr/media/delete/${relId}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const ListContract = async (
    payload: PaggingListPayload,
    token: string
  ): Promise<ApiGenericResponse<VendorContractResponse[] | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<VendorContractResponse[]>>(
        `${UrlEndpoint}/v1/Vendor/contract/list`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const InsertContract = async (
    payload: VendorContractInsertPayload,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/contract/insert`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const GetContractDetail = async (
    id: string,
    token: string
  ): Promise<ApiGenericResponse<VendorContractResponse | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.get<ApiGenericResponse<VendorContractResponse>>(
        `${UrlEndpoint}/v1/Vendor/contract/detail/${id}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const ListPayment = async (
    payload: PaggingListPayload,
    token: string
  ): Promise<ApiGenericResponse<ContractPaymentResponse[] | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<ContractPaymentResponse[]>>(
        `${UrlEndpoint}/v1/Vendor/payment/list`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const GetPaymentDetail = async (
    id: string,
    token: string
  ): Promise<ApiGenericResponse<ContractPaymentResponse | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.get<ApiGenericResponse<ContractPaymentResponse>>(
        `${UrlEndpoint}/v1/Vendor/payment/detail/${id}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const GetPaymentByContractId = async (
    contractId: string,
    token: string
  ): Promise<ApiGenericResponse<ContractPaymentResponse | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.get<ApiGenericResponse<ContractPaymentResponse>>(
        `${UrlEndpoint}/v1/Vendor/payment/contract/${contractId}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        return {
          statusCode: err.response?.status || RES_CODE_SERVER_ERROR,
          data: null,
          message: err.response?.data?.message || "Payment not found",
          error: null,
        };
      }
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const InsertPayment = async (
    payload: ContractPaymentInsertPayload,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/payment/insert`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const UpdatePayment = async (
    payload: ContractPaymentUpdatePayload,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.put<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/payment/update`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const DeletePayment = async (
    id: string,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.delete<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/payment/delete/${id}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const UploadPaymentAttachment = async (
    formData: FormData,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/payment/attachment/upload`,
        formData,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "multipart/form-data",
          },
        }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const DeletePaymentAttachment = async (
    id: string,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.delete<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/payment/attachment/delete/${id}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const GetTopAttachmentsByTopId = async (
    topId: string,
    token: string
  ): Promise<ApiGenericResponse<ContractPaymentTopAttachmentResponse[] | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.get<ApiGenericResponse<ContractPaymentTopAttachmentResponse[]>>(
        `${UrlEndpoint}/v1/Vendor/payment/top/${topId}/attachments`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const UploadTopAttachment = async (
    formData: FormData,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/payment/top/attachment/upload`,
        formData,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "multipart/form-data",
          },
        }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const DeleteTopAttachment = async (
    id: string,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.delete<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/payment/top/attachment/delete/${id}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const UpdateContractTopStatus = async (
    payload: ContractTopStatusUpdatePayload,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.put<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/payment/top/status`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const RecalculateMasterPayment = async (
    contractPaymentId: string,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/payment/recalculate/${contractPaymentId}`,
        {},
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const GetCostGovernanceByContractId = async (
    contractId: string,
    token: string
  ): Promise<ApiGenericResponse<ContractCostGovernanceResponse | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.get<ApiGenericResponse<ContractCostGovernanceResponse>>(
        `${UrlEndpoint}/v1/Vendor/contract/cost-governance/${contractId}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const SaveCostGovernance = async (
    payload: ContractCostGovernanceSavePayload,
    token: string
  ): Promise<ApiGenericResponse<string | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.post<ApiGenericResponse<string>>(
        `${UrlEndpoint}/v1/Vendor/contract/cost-governance/save`,
        payload,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  const GetCostGovHistoryList = async (
    contractId: string,
    token: string
  ): Promise<ApiGenericResponse<ContractCostGovHistoryResponse[] | null> | null> => {
    setIsLoading(true);
    setError(null);
    const UrlEndpoint: string = buildUrlPort(ENDPOINT_API_BASEURL, ENDPOINT_PORT_BASIC);
    try {
      const response = await axiosInstance.get<ApiGenericResponse<ContractCostGovHistoryResponse[]>>(
        `${UrlEndpoint}/v1/Vendor/contract/cost-governance/history/${contractId}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsLoading(false);
      return response.data;
    } catch (err) {
      setIsLoading(false);
      if (axios.isAxiosError(err)) {
        setError(err.response?.data?.message || "An error occurred.");
        return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: err.response?.data?.message || "Error", error: null };
      }
      setError("An unknown error occurred.");
      return { statusCode: RES_CODE_SERVER_ERROR, data: null, message: "Error", error: null };
    }
  };

  return {
    List,
    ListTdr,
    ListContract,
    InsertContract,
    GetContractDetail,
    ListPayment,
    GetPaymentDetail,
    GetPaymentByContractId,
    InsertPayment,
    UpdatePayment,
    DeletePayment,
    UploadPaymentAttachment,
    DeletePaymentAttachment,
    GetTopAttachmentsByTopId,
    UploadTopAttachment,
    DeleteTopAttachment,
    UpdateContractTopStatus,
    RecalculateMasterPayment,
    GetCostGovernanceByContractId,
    SaveCostGovernance,
    GetCostGovHistoryList,
    GetDetailById,
    Register,
    Update,
    InsertTdr,
    UpdateTdr,
    DeleteTdrMedia,
    isLoading,
    error,
  };
};

export default useVendor;
